"use client";

import { create } from "zustand";

export type Lang = "eng" | "esp" | "ru" | "fr" | "it" | "de" | "uk";

const STORAGE_KEY = "inftour_lang";
const LANG_TO_HTML: Record<Lang, string> = { eng: "en", esp: "es", ru: "ru", fr: "fr", it: "it", de: "de", uk: "uk" };
const VALID_LANGS: Lang[] = ["eng", "esp", "ru", "fr", "it", "de", "uk"];

/** Map browser language tag (e.g. "en", "es-ES") to our Lang. Uses first match from navigator.languages. */
function getBrowserLang(): Lang {
  if (typeof navigator === "undefined") return "eng";
  const tags = [navigator.language, ...(navigator.languages || [])].filter(Boolean);
  for (const tag of tags) {
    const code = tag.toLowerCase().split("-")[0];
    if (code === "en") return "eng";
    if (code === "es") return "esp";
    if (code === "ru") return "ru";
    if (code === "fr") return "fr";
    if (code === "it") return "it";
    if (code === "de") return "de";
    if (code === "uk") return "uk";
  }
  return "eng";
}

type LangStrings = { eng: string; esp: string; ru: string; fr: string; it: string; de: string; uk: string };
type TranslationMap = Record<string, LangStrings>;

const translations: TranslationMap = {
  // Nav & brand
  calpeCollection: {
    eng: "Calpe Collection",
    esp: "Calpe Collection",
    ru: "Коллекция Кальпе",
    fr: "Calpe Collection",
    it: "Calpe Collection",
    de: "Calpe Collection",
    uk: "Колекція Кальпе",
  },
  reservaDirecta: { eng: "Direct booking", esp: "Reserva directa", ru: "Прямое бронирование", fr: "Réservation directe", it: "Prenotazione diretta", de: "Direktbuchung", uk: "Пряме бронювання" },
  experiencias: { eng: "Experiences", esp: "Experiencias", ru: "Впечатления", fr: "Expériences", it: "Esperienze", de: "Erlebnisse", uk: "Враження" },
  services: { eng: "Services", esp: "Servicios", ru: "Услуги", fr: "Services", it: "Servizi", de: "Dienstleistungen", uk: "Послуги" },
  revista: { eng: "Magazine", esp: "Revista", ru: "Журнал", fr: "Magazine", it: "Rivista", de: "Magazin", uk: "Журнал" },
  lobby: { eng: "Lobby", esp: "Lobby", ru: "Лобби", fr: "Lobby", it: "Lobby", de: "Lobby", uk: "Лобі" },
  aiAgent: { eng: "AI Agent", esp: "Agente IA", ru: "ИИ-агент", fr: "Agent IA", it: "Agente IA", de: "KI-Agent", uk: "ІІ-агент" },
  openAIChat: { eng: "Open AI Agent chat", esp: "Abrir chat del agente IA", ru: "Открыть чат ИИ-агента", fr: "Ouvrir le chat de l'agent IA", it: "Apri chat agente IA", de: "KI-Agent-Chat öffnen", uk: "Відкрити чат ІІ-агента" },

  // Footer
  footerTagline: {
    eng: "Exclusive apartment rentals in Calpe.",
    esp: "Alquiler exclusivo de apartamentos en Calpe.",
    ru: "Эксклюзивная аренда апартаментов в Кальпе.",
    fr: "Location exclusive d'appartements à Calpe.",
    it: "Affitti esclusivi di appartamenti a Calpe.",
    de: "Exklusive Apartment-Vermietung in Calpe.",
    uk: "Ексклюзивна оренда апартаментів у Кальпе.",
  },
  footerLicense: {
    eng: "Tour operator license: EGVT-XXX-A.",
    esp: "Licencia de agencia: EGVT-XXX-A.",
    ru: "Лицензия туристического оператора: EGVT-XXX-A.",
    fr: "Licence tour-opérateur : EGVT-XXX-A.",
    it: "Licenza tour operator: EGVT-XXX-A.",
    de: "Reiseveranstalter-Lizenz: EGVT-XXX-A.",
    uk: "Ліцензія туроператора: EGVT-XXX-A.",
  },
  navigation: { eng: "Navigation", esp: "Navegación", ru: "Навигация", fr: "Navigation", it: "Navigazione", de: "Navigation", uk: "Навігація" },
  contact: { eng: "Contact", esp: "Contacto", ru: "Связь", fr: "Contact", it: "Contatti", de: "Kontakt", uk: "Контакти" },
  allRightsReserved: {
    eng: "© 2026 INFTOUR. All rights reserved.",
    esp: "© 2026 INFTOUR. Todos los derechos reservados.",
    ru: "© 2026 INFTOUR. Все права защищены.",
    fr: "© 2026 INFTOUR. Tous droits réservés.",
    it: "© 2026 INFTOUR. Tutti i diritti riservati.",
    de: "© 2026 INFTOUR. Alle Rechte vorbehalten.",
    uk: "© 2026 INFTOUR. Усі права захищено.",
  },
  privacyPolicy: { eng: "Privacy Policy", esp: "Política de privacidad", ru: "Политика конфиденциальности", fr: "Politique de confidentialité", it: "Informativa sulla privacy", de: "Datenschutz", uk: "Політика конфіденційності" },
  termsOfService: { eng: "Terms of Service", esp: "Términos de uso", ru: "Условия использования", fr: "Conditions d'utilisation", it: "Termini di utilizzo", de: "Nutzungsbedingungen", uk: "Умови використання" },

  // TopBar
  sea: { eng: "Sea", esp: "Mar", ru: "Море", fr: "Mer", it: "Mare", de: "Meer", uk: "Море" },
  seaTempTitle: { eng: "Sea temperature in Calpe", esp: "Temperatura del mar en Calpe", ru: "Температура моря в Кальпе", fr: "Température de la mer à Calpe", it: "Temperatura del mare a Calpe", de: "Wassertemperatur in Calpe", uk: "Температура моря в Кальпе" },
  calpeLiveWebcam: { eng: "Calpe Live Webcam", esp: "Webcam en vivo Calpe", ru: "Веб-камера Кальпе", fr: "Webcam en direct Calpe", it: "Webcam live Calpe", de: "Calpe Live-Webcam", uk: "Веб-камера Кальпе" },
  openInNewTab: { eng: "Open in new tab", esp: "Abrir en nueva pestaña", ru: "Открыть в новой вкладке", fr: "Ouvrir dans un nouvel onglet", it: "Apri in nuova scheda", de: "In neuem Tab öffnen", uk: "Відкрити в новій вкладці" },
  close: { eng: "Close", esp: "Cerrar", ru: "Закрыть", fr: "Fermer", it: "Chiudi", de: "Schließen", uk: "Закрити" },

  // Nav mobile menu
  openMenu: { eng: "Open menu", esp: "Abrir menú", ru: "Открыть меню", fr: "Ouvrir le menu", it: "Apri menu", de: "Menü öffnen", uk: "Відкрити меню" },
  closeMenu: { eng: "Close menu", esp: "Cerrar menú", ru: "Закрыть меню", fr: "Fermer le menu", it: "Chiudi menu", de: "Menü schließen", uk: "Закрити меню" },

  // AI Agent chat
  closeChat: { eng: "Close chat", esp: "Cerrar chat", ru: "Закрыть чат", fr: "Fermer le chat", it: "Chiudi chat", de: "Chat schließen", uk: "Закрити чат" },
  aiAgentWelcome: {
    eng: "Hello, I'm the INFTOUR assistant. How can I help you today? Ask me about bookings, experiences in Calpe or anything else.",
    esp: "Hola, soy el asistente de INFTOUR. ¿En qué puedo ayudarte hoy? Puedes preguntarme sobre reservas, experiencias en Calpe o cualquier otro tema.",
    ru: "Здравствуйте, я помощник INFTOUR. Чем могу помочь? Спрашивайте о бронировании, впечатлениях в Кальпе или о чём угодно.",
    fr: "Bonjour, je suis l'assistant INFTOUR. Comment puis-je vous aider ? Posez-moi des questions sur les réservations, les expériences à Calpe ou autre.",
    it: "Ciao, sono l'assistente INFTOUR. Come posso aiutarti? Chiedimi prenotazioni, esperienze a Calpe o altro.",
    de: "Hallo, ich bin der INFTOUR-Assistent. Wie kann ich Ihnen helfen? Fragen Sie nach Buchungen, Erlebnissen in Calpe oder anderem.",
    uk: "Вітаю, я помічник INFTOUR. Чим можу допомогти? Питайте про бронювання, враження в Кальпе або будь-що інше.",
  },
  aiAgentReply: {
    eng: "Thank you for your message. An agent will reply shortly.",
    esp: "Gracias por tu mensaje. Un agente te responderá en breve.",
    ru: "Спасибо за сообщение. Агент ответит вам в ближайшее время.",
    fr: "Merci pour votre message. Un agent vous répondra sous peu.",
    it: "Grazie per il messaggio. Un agente risponderà a breve.",
    de: "Vielen Dank für Ihre Nachricht. Ein Agent wird sich in Kürze melden.",
    uk: "Дякуємо за повідомлення. Агент відповість найближчим часом.",
  },
  writeMessage: {
    eng: "Type your message...",
    esp: "Escribe tu mensaje...",
    ru: "Введите сообщение...",
    fr: "Tapez votre message...",
    it: "Scrivi il tuo messaggio...",
    de: "Nachricht eingeben...",
    uk: "Введіть повідомлення...",
  },
  send: { eng: "Send", esp: "Enviar", ru: "Отправить", fr: "Envoyer", it: "Invia", de: "Senden", uk: "Надіслати" },

  // Home
  loadingCalendar: {
    eng: "Loading calendar...",
    esp: "Cargando calendario...",
    ru: "Загрузка календаря...",
    fr: "Chargement du calendrier...",
    it: "Caricamento calendario...",
    de: "Kalender wird geladen...",
    uk: "Завантаження календаря...",
  },
  bookingCalendar: { eng: "Booking calendar", esp: "Calendario de reservas", ru: "Календарь бронирования", fr: "Calendrier des réservations", it: "Calendario prenotazioni", de: "Buchungskalender", uk: "Календар бронювань" },

  // Pages – Experiencias (Ecosystem)
  experienciasTitle: { eng: "Experiences", esp: "Experiencias", ru: "Впечатления", fr: "Expériences", it: "Esperienze", de: "Erlebnisse", uk: "Враження" },
  experienciasContent: {
    eng: "Experiences content.",
    esp: "Contenido de Experiencias.",
    ru: "Содержание раздела «Впечатления».",
    fr: "Contenu Expériences.",
    it: "Contenuto Esperienze.",
    de: "Inhalt Erlebnisse.",
    uk: "Зміст розділу «Враження».",
  },
  expHeroTitle: {
    eng: "Ecosystem of rest",
    esp: "Ecosistema de descanso",
    ru: "Экосистема отдыха",
    fr: "Écosystème du repos",
    it: "Ecosistema del riposo",
    de: "Ökosystem der Erholung",
    uk: "Екосистема відпочинку",
  },
  expHeroDesc: {
    eng: "We created a guide that will replace a tour bureau for you.",
    esp: "Hemos creado una guía que te sustituirá la oficina de excursions.",
    ru: "Мы создали гид, который заменит вам экскурсионное бюро.",
    fr: "Nous avons créé un guide qui remplacera l'agence de voyages pour vous.",
    it: "Abbiamo creato una guida che sostituirà l'ufficio escursioni per te.",
    de: "Wir haben einen Reiseführer erstellt, der Ihnen das Reisebüro ersetzt.",
    uk: "Ми створили гід, який замінить вам туристичне бюро.",
  },
  expAIGuide: { eng: "AI guide", esp: "Guía IA", ru: "АИ гид", fr: "Guide IA", it: "Guida IA", de: "KI-Reiseführer", uk: "ШІ-гід" },
  expAIGuideDesc: {
    eng: "Clear list of what our AI assistant can do: bookings, availability, recommendations for restaurants and activities, tips for Ifach and Salinas, events calendar, and more. Open the chat from the menu.",
    esp: "Lista clara de lo que hace nuestro asistente IA: reservas, disponibilidad, recomendaciones de restaurantes y actividades, consejos para el Ifach y Salinas, calendario de eventos y más. Abre el chat desde el menú.",
    ru: "Чёткий список возможностей ИИ-гида: бронирование, наличие мест, рекомендации ресторанов и активностей, советы по Ифачу и Салинас, календарь событий и другое. Откройте чат в меню.",
    fr: "Liste claire de ce que fait notre assistant IA : réservations, disponibilité, recommandations restaurants et activités, conseils Ifach et Salinas, calendrier des événements. Ouvrez le chat depuis le menu.",
    it: "Elenco chiaro di cosa fa il nostro assistente IA: prenotazioni, disponibilità, consigli su ristoranti e attività, Ifach e Salinas, calendario eventi. Apri la chat dal menu.",
    de: "Klare Liste der KI-Assistenten-Funktionen: Buchungen, Verfügbarkeit, Empfehlungen für Restaurants und Aktivitäten, Tipps zu Ifach und Salinas, Veranstaltungskalender. Chat im Menü öffnen.",
    uk: "Чіткий список можливостей ШІ-гіда: бронювання, наявність, рекомендації ресторанів та активностей, поради щодо Іфачу та Салінас, календар подій. Відкрийте чат у меню.",
  },
  expGastronomy: { eng: "Tastes – Gastronomy", esp: "Sabores – Gastronomía", ru: "Вкусы – Гастрономия", fr: "Saveurs – Gastronomie", it: "Sapori – Gastronomia", de: "Geschmack – Gastronomie", uk: "Смаки – Гастрономія" },
  expGastronomyDesc: {
    eng: "Guide to restaurants, markets, fish market, and recommended local recipes.",
    esp: "Guía de restaurantes, mercados, lonja, y recetas locales recomendadas.",
    ru: "Гид по ресторанам, рынкам, рыбной бирже и рекомендуемым местным рецептам.",
    fr: "Guide des restaurants, marchés, criée et recettes locales recommandées.",
    it: "Guida a ristoranti, mercati, mercato del pesce e ricette locali consigliate.",
    de: "Führer zu Restaurants, Märkten, Fischmarkt und empfohlenen lokalen Rezepten.",
    uk: "Гід по ресторанах, ринках, рибній біржі та рекомендованих місцевих рецептах.",
  },
  expRestaurants: { eng: "Restaurants", esp: "Restaurantes", ru: "Рестораны", fr: "Restaurants", it: "Ristoranti", de: "Restaurants", uk: "Ресторани" },
  expMarkets: { eng: "Markets, fish market, grocery stores", esp: "Mercados, lonja, tiendas de alimentación", ru: "Рынки, рыбные биржи, продуктовые магазины", fr: "Marchés, criée, épiceries", it: "Mercati, mercato del pesce, alimentari", de: "Märkte, Fischmarkt, Lebensmittelgeschäfte", uk: "Ринки, рибні біржі, продуктові магазини" },
  expRecipes: { eng: "Local recipes", esp: "Recetas locales", ru: "Местные рецепты блюд", fr: "Recettes locales", it: "Ricette locali", de: "Lokale Rezepte", uk: "Місцеві рецепти" },
  expNature: { eng: "Nature", esp: "Naturaleza", ru: "Природа", fr: "Nature", it: "Natura", de: "Natur", uk: "Природа" },
  expNatureDesc: {
    eng: "Trails in nature reserves: tips for climbing Ifach, routes along Salinas, seaside walks.",
    esp: "Rutas por reservas naturales: consejos para subir al Ifach, rutas por Salinas, paseos junto al mar.",
    ru: "Тропы по природным заповедникам: советы по восхождению на Ифач, маршруты вдоль Салинас, прогулки вдоль моря.",
    fr: "Sentiers en réserves naturelles : conseils pour l'Ifach, itinéraires Salinas, promenades en bord de mer.",
    it: "Sentieri nelle riserve naturali: consigli per l'Ifach, percorsi Salinas, passeggiate sul mare.",
    de: "Wanderwege in Naturschutzgebieten: Tipps für Ifach, Routen an den Salinas, Strandspaziergänge.",
    uk: "Стежки в природних заповідниках: поради щодо Іфачу, маршрути вздовж Салінас, прогулянки біля моря.",
  },
  expIfach: { eng: "Climbing Ifach", esp: "Subida al Ifach", ru: "Восхождение на Ифач", fr: "Ascension de l'Ifach", it: "Salita all'Ifach", de: "Ifach besteigen", uk: "Підйом на Іфач" },
  expSalinas: { eng: "Hiking along Salinas", esp: "Rutas por Salinas", ru: "Пешие маршруты вдоль Салинас", fr: "Randonnées Salinas", it: "Escursioni Salinas", de: "Wanderungen an den Salinas", uk: "Піші маршрути вздовж Салінас" },
  expSeaside: { eng: "Seaside walks", esp: "Paseos junto al mar", ru: "Прогулки вдоль моря", fr: "Promenades en bord de mer", it: "Passeggiate sul mare", de: "Strandspaziergänge", uk: "Прогулянки вздовж моря" },
  expFamily: { eng: "Family", esp: "Familia", ru: "Семья", fr: "Famille", it: "Famiglia", de: "Familie", uk: "Сім'я" },
  expFamilyDesc: {
    eng: "Leisure with family and friends.",
    esp: "Ocio en familia y con amigos.",
    ru: "Досуг с семьей и друзьями.",
    fr: "Loisirs en famille et entre amis.",
    it: "Tempo libero in famiglia e con amici.",
    de: "Freizeit mit Familie und Freunden.",
    uk: "Дозвіллє з сім'єю та друзями.",
  },
  expBBQ: { eng: "BBQ, Virtual arena & playgrounds", esp: "Barbacoas, arena virtual y parques", ru: "BBQ, Virtualnaya arena и детские площадки", fr: "BBQ, arène virtuelle et aires de jeux", it: "BBQ, arena virtuale e parchi giochi", de: "BBQ, virtuelle Arena und Spielplätze", uk: "BBQ, віртуальна арена та дитячі майданчики" },
  expFeria: { eng: "Feria", esp: "Feria", ru: "Feria", fr: "Feria", it: "Feria", de: "Feria", uk: "Feria" },
  expCityGuide: { eng: "Electronic city guide", esp: "Guía electrónica de la ciudad", ru: "Электронный гид по городу", fr: "Guide électronique de la ville", it: "Guida elettronica della città", de: "Elektronischer Stadtführer", uk: "Електронний гід по місту" },
  expEventsCalendar: { eng: "Events calendar", esp: "Calendario de eventos", ru: "Календарь событий", fr: "Calendrier des événements", it: "Calendario eventi", de: "Veranstaltungskalender", uk: "Календар подій" },
  expRelax: { eng: "Relax", esp: "Relax", ru: "Релакс", fr: "Relax", it: "Relax", de: "Entspannung", uk: "Релакс" },
  expRelaxDesc: {
    eng: "Beaches and SPA.",
    esp: "Playas y SPA.",
    ru: "Пляжи и СПА.",
    fr: "Plages et SPA.",
    it: "Spiagge e SPA.",
    de: "Strände und SPA.",
    uk: "Пляжі та СПА.",
  },
  expSport: { eng: "Lifestyle – Sport", esp: "Estilo de vida – Deporte", ru: "Образ жизни – Спорт", fr: "Style de vie – Sport", it: "Stile di vita – Sport", de: "Lifestyle – Sport", uk: "Стиль життя – Спорт" },
  expSportDesc: {
    eng: "Cycling, sports facilities, equipment rental, and events calendar.",
    esp: "Ciclismo, instalaciones deportivas, alquiler de material y calendario de eventos.",
    ru: "Вело прогулки, спортивные сооружения, прокат инвентаря и календарь мероприятий.",
    fr: "Vélo, installations sportives, location de matériel et calendrier des événements.",
    it: "Ciclismo, strutture sportive, noleggio attrezzature e calendario eventi.",
    de: "Radfahren, Sportanlagen, Ausrüstungsverleih und Veranstaltungskalender.",
    uk: "Велопрогулянки, спортивні споруди, прокат інвентарю та календар подій.",
  },
  expCycling: { eng: "Cycling", esp: "Ciclismo", ru: "Вело прогулки", fr: "Vélo", it: "Ciclismo", de: "Radfahren", uk: "Велопрогулянки" },
  expSportsFacilities: { eng: "Sports facilities in Calpe", esp: "Instalaciones deportivas en Calpe", ru: "Спортивные сооружения Кальпе", fr: "Installations sportives à Calpe", it: "Strutture sportive a Calpe", de: "Sportanlagen in Calpe", uk: "Спортивні споруди в Кальпе" },
  expEquipmentRental: { eng: "Sports equipment rental", esp: "Alquiler de material deportivo", ru: "Прокат спортивного инвентаря", fr: "Location de matériel sportif", it: "Noleggio attrezzature sportive", de: "Sportausrüstungsverleih", uk: "Прокат спортивного інвентарю" },
  expSportsEvents: { eng: "Sports events & calendar", esp: "Eventos deportivos y calendario", ru: "Спортивные мероприятия, календарь", fr: "Événements sportifs et calendrier", it: "Eventi sportivi e calendario", de: "Sportveranstaltungen und Kalender", uk: "Спортивні події та календар" },
  expHeroLabel: { eng: "Leisure ecosystem", esp: "Ecosistema de Ocio", ru: "Экосистема досуга", fr: "Écosystème de loisirs", it: "Ecosistema del tempo libero", de: "Freizeit-Ökosystem", uk: "Екосистема дозвілля" },
  expPageTitle: { eng: "INFTOUR Experiences", esp: "Experiencias INFTOUR", ru: "Впечатления INFTOUR", fr: "Expériences INFTOUR", it: "Esperienze INFTOUR", de: "INFTOUR Erlebnisse", uk: "Враження INFTOUR" },
  expHeroDescLong: {
    eng: "We have created an exclusive guide that will completely replace the traditional excursion office. Immerse yourself in the authentic life of Calpe with our carefully selected recommendations.",
    esp: "Hemos creado una guía exclusiva que reemplazará por completo a la oficina de excursiones tradicional. Sumérgete en la auténtica vida de Calpe con nuestras recomendaciones cuidadosamente seleccionadas.",
    ru: "Мы создали эксклюзивный гид, который полностью заменит традиционное экскурсионное бюро. Погрузитесь в подлинную жизнь Кальпе с нашими тщательно подобранными рекомендациями.",
    fr: "Nous avons créé un guide exclusif qui remplacera complètement l'office d'excursions traditionnel. Plongez dans la vie authentique de Calpe avec nos recommandations soigneusement sélectionnées.",
    it: "Abbiamo creato una guida esclusiva che sostituirà completamente l'ufficio escursioni tradizionale. Immergiti nella vita autentica di Calpe con le nostre raccomandazioni selezionate.",
    de: "Wir haben einen exklusiven Guide erstellt, der das traditionelle Ausflugsbüro vollständig ersetzen wird. Tauchen Sie ein in das authentische Leben von Calpe mit unseren sorgfältig ausgewählten Empfehlungen.",
    uk: "Ми створили ексклюзивний гід, який повністю замінить традиційне екскурсійне бюро. Пориньте в справжнє життя Кальпе з нашими ретельно підібраними рекомендаціями.",
  },
  expGastronomySub: { eng: "Local gastronomy", esp: "Gastronomía local", ru: "Местная гастрономия", fr: "Gastronomie locale", it: "Gastronomia locale", de: "Lokale Gastronomie", uk: "Місцева гастрономія" },
  expRestaurantsDesc: { eng: "From fine dining to traditional tapas.", esp: "De la alta cocina a las tapas tradicionales.", ru: "От высокой кухни до традиционных тапас.", fr: "De la haute cuisine aux tapas traditionnelles.", it: "Dalla cucina raffinata alle tapas tradizionali.", de: "Von Feinschmecker-Küche bis zu traditionellen Tapas.", uk: "Від високої кухні до традиційних тапас." },
  expMarketsDesc: { eng: "Fish auction and fresh produce shops.", esp: "Subasta de pescado y tiendas de productos frescos.", ru: "Рыбный аукцион и магазины свежих продуктов.", fr: "Vente aux enchères de poisson et magasins de produits frais.", it: "Asta del pesce e negozi di prodotti freschi.", de: "Fischversteigerung und Frischeproduktläden.", uk: "Рибний аукціон та магазини свіжих продуктів." },
  expRecipesDesc: { eng: "Learn to cook Llauna de Calp or Arròs del Senyoret.", esp: "Aprende a cocinar Llauna de Calp o Arròs del Senyoret.", ru: "Научитесь готовить Llauna de Calp или Arròs del Senyoret.", fr: "Apprenez à cuisiner la Llauna de Calp ou l'Arròs del Senyoret.", it: "Impara a cucinare Llauna de Calp o Arròs del Senyoret.", de: "Lernen Sie Llauna de Calp oder Arròs del Senyoret zu kochen.", uk: "Навчіться готувати Llauna de Calp або Arròs del Senyoret." },
  expNatureSub: { eng: "Trails and reserves", esp: "Senderos y Reservas", ru: "Тропы и заповедники", fr: "Sentiers et réserves", it: "Sentieri e riserve", de: "Wanderwege und Reservate", uk: "Стежки та заповідники" },
  expIfachDesc: { eng: "Safety tips, required permits and best times to climb the symbol of the Costa Blanca.", esp: "Consejos de seguridad, permisos necesarios y las mejores horas para subir al símbolo de la Costa Blanca.", ru: "Советы по безопасности, необходимые разрешения и лучшее время для восхождения на символ Коста-Бланки.", fr: "Conseils de sécurité, permis nécessaires et meilleures heures pour gravir le symbole de la Costa Blanca.", it: "Consigli di sicurezza, permessi necessari e migliori orari per salire sul simbolo della Costa Blanca.", de: "Sicherheitstipps, erforderliche Genehmigungen und beste Zeiten für den Aufstieg zum Symbol der Costa Blanca.", uk: "Поради з безпеки, необхідні дозволи та найкращий час для підйому на символ Коста-Бланки." },
  expSalinasDesc: { eng: "Flamingo watching and flat walks ideal for sunset.", esp: "Observación de flamencos y paseos llanos ideales para el atardecer.", ru: "Наблюдение за фламинго и равнинные прогулки, идеальные для заката.", fr: "Observation des flamants et promenades plates idéales au coucher du soleil.", it: "Osservazione dei fenicotteri e passeggiate piatte ideali per il tramonto.", de: "Flamingo-Beobachtung und flache Spaziergänge ideal bei Sonnenuntergang.", uk: "Спостереження за фламінго та рівнинні прогулянки, ідеальні для заходу сонця." },
  expSeasideDesc: { eng: "Eco routes along the cliffs of Benissa and Calpe seafront promenades.", esp: "Rutas ecológicas por los acantilados de Benissa y paseos marítimos de Calpe.", ru: "Экомаршруты по скалам Бениссы и набережные Кальпе.", fr: "Parcours écologiques le long des falaises de Benissa et promenades en front de mer de Calpe.", it: "Percorsi ecologici lungo le scogliere di Benissa e passeggiate sul lungomare di Calpe.", de: "Ökorouten entlang der Klippen von Benissa und Calpes Strandpromenaden.", uk: "Екомаршрути вздовж скель Бенісси та набережні Кальпе." },
  expFamilySub: { eng: "Shared leisure", esp: "Ocio compartido", ru: "Совместный досуг", fr: "Loisirs partagés", it: "Tempo libero condiviso", de: "Gemeinsame Freizeit", uk: "Спільний дозвіллє" },
  expViewEventsCalendar: { eng: "View events calendar", esp: "Ver Calendario de Eventos", ru: "Календарь событий", fr: "Voir le calendrier des événements", it: "Vedi calendario eventi", de: "Veranstaltungskalender anzeigen", uk: "Переглянути календар подій" },
  expSportSub: { eng: "Active sport", esp: "Deporte activo", ru: "Активный спорт", fr: "Sport actif", it: "Sport attivo", de: "Aktiver Sport", uk: "Активний спорт" },
  expRelaxDescLong: {
    eng: "Discover hidden coves with crystal-clear waters, wide sandy beaches and the best wellness centres to unwind.",
    esp: "Descubre las calas escondidas de aguas cristalinas, las amplias playas de arena fina y los mejores centros de bienestar para desconectar.",
    ru: "Откройте для себя укромные бухты с кристально чистой водой, широкие песчаные пляжи и лучшие спа-центры для отдыха.",
    fr: "Découvrez les criques cachées aux eaux cristallines, les vastes plages de sable fin et les meilleurs centres de bien-être pour déconnecter.",
    it: "Scopri le calette nascoste con acque cristalline, le ampie spiagge di sabbia fine e i migliori centri benessere per staccare.",
    de: "Entdecken Sie versteckte Buchten mit kristallklarem Wasser, weite Sandstrände und die besten Wellnesszentren zum Abschalten.",
    uk: "Відкрийте для себе укриті бухти з кришталево чистою водою, широкі піщані пляжі та найкращі спа-центри для відпочинку.",
  },
  expExploreCatalog: { eng: "Explore catalog", esp: "Explorar catálogo", ru: "Каталог", fr: "Explorer le catalogue", it: "Esplora catalogo", de: "Katalog entdecken", uk: "Переглянути каталог" },

  // Revista (Magazine)
  revistaTitle: { eng: "Rental properties magazine", esp: "Revista de alquileres", ru: "Журнал об аренде", fr: "Magazine locations", it: "Rivista affitti", de: "Mietobjekte-Magazin", uk: "Журнал про оренду" },
  revistaTagline: {
    eng: "Discover our selection of apartments and villas in Calpe.",
    esp: "Descubre nuestra selección de apartamentos y villas en Calpe.",
    ru: "Подборка апартаментов и вилл в Кальпе.",
    fr: "Découvrez notre sélection d'appartements et villas à Calpe.",
    it: "Scopri la nostra selezione di appartamenti e ville a Calpe.",
    de: "Entdecken Sie unsere Auswahl an Apartments und Villen in Calpe.",
    uk: "Ознайомтесь з нашою підбіркою апартаментів та вілл у Кальпе.",
  },
  revistaPlaceholderIntro: {
    eng: "Your next magazine issue will appear here. Upload a PDF to public/magazine/ and set MAGAZINE_PDF_PATH in app/config/magazine.ts to display it.",
    esp: "Tu próxima revista aparecerá aquí. Sube un PDF a public/magazine/ y configura MAGAZINE_PDF_PATH en app/config/magazine.ts.",
    ru: "Здесь будет отображаться журнал. Положите PDF в public/magazine/ и укажите MAGAZINE_PDF_PATH в app/config/magazine.ts.",
    fr: "Votre prochain numéro apparaîtra ici. Uploadez un PDF dans public/magazine/ et définissez MAGAZINE_PDF_PATH dans app/config/magazine.ts.",
    it: "Il prossimo numero apparirà qui. Carica un PDF in public/magazine/ e imposta MAGAZINE_PDF_PATH in app/config/magazine.ts.",
    de: "Die nächste Ausgabe erscheint hier. PDF in public/magazine/ hochladen und MAGAZINE_PDF_PATH in app/config/magazine.ts setzen.",
    uk: "Тут з'явиться журнал. Завантажте PDF у public/magazine/ та вкажіть MAGAZINE_PDF_PATH у app/config/magazine.ts.",
  },
  revistaDownload: { eng: "Download magazine", esp: "Descargar revista", ru: "Скачать журнал", fr: "Télécharger le magazine", it: "Scarica rivista", de: "Magazin herunterladen", uk: "Завантажити журнал" },
  revistaSpread1Title: {
    eng: "Apartments with sea views",
    esp: "Apartamentos con vistas al mar",
    ru: "Апартаменты с видом на море",
    fr: "Appartements avec vue mer",
    it: "Appartamenti con vista mare",
    de: "Apartments mit Meerblick",
    uk: "Апартаменти з видом на море",
  },
  revistaSpread1Text: {
    eng: "Hand-picked flats and penthouses in Calpe with direct views of the Mediterranean and the Peñón de Ifach. Modern amenities and easy access to the beach.",
    esp: "Pisos y áticos seleccionados en Calpe con vistas al Mediterráneo y al Peñón de Ifach. Todas las comodidades y cerca de la playa.",
    ru: "Подобранные апартаменты и пентхаусы в Кальпе с видом на Средиземное море и Пеньон-де-Ифач. Современные удобства и близко к пляжу.",
    fr: "Appartements et penthouses sélectionnés à Calpe avec vue sur la Méditerranée et le Peñón de Ifach. Confort moderne et accès facile à la plage.",
    it: "Appartamenti e attici selezionati a Calpe con vista sul Mediterraneo e sul Peñón de Ifach. Comfort moderni e facile accesso alla spiaggia.",
    de: "Ausgewählte Wohnungen und Penthäuser in Calpe mit Blick aufs Mittelmeer und den Peñón de Ifach. Moderne Ausstattung und Strandnähe.",
    uk: "Підібрані апартаменти та пентхауси в Кальпе з видом на Середземне море та Пеньйон-де-Іфач. Сучасні зручності та близько до пляжу.",
  },
  revistaSpread2Title: {
    eng: "Pools & outdoor living",
    esp: "Piscinas y vida al aire libre",
    ru: "Бассейны и отдых на открытом воздухе",
    fr: "Piscines et vie en plein air",
    it: "Piscine e vita all'aperto",
    de: "Pools und Outdoor-Living",
    uk: "Басейни та відпочинок на відкритому повітрі",
  },
  revistaSpread2Text: {
    eng: "Properties with private or communal pools, terraces and gardens. Enjoy the Costa Blanca lifestyle from your own space.",
    esp: "Propiedades con piscina privada o comunitaria, terrazas y jardines. Disfruta del estilo de vida de la Costa Blanca desde tu espacio.",
    ru: "Объекты с частным или общим бассейном, террасами и садами. Наслаждайтесь жизнью на Коста-Бланке у себя.",
    fr: "Biens avec piscine privée ou commune, terrasses et jardins. Profitez du style de vie Costa Blanca depuis chez vous.",
    it: "Immobili con piscina privata o comune, terrazze e giardini. Goditi lo stile di vita Costa Blanca dal tuo spazio.",
    de: "Objekte mit privatem oder Gemeinschaftspool, Terrassen und Gärten. Genießen Sie den Costa-Blanca-Lifestyle in den eigenen vier Wänden.",
    uk: "Об'єкти з приватним або спільним басейном, терасами та садами. Насолоджуйтесь життям на Коста-Бланці у себе.",
  },
  revistaSpread3Title: {
    eng: "Villas for families & groups",
    esp: "Villas para familias y grupos",
    ru: "Виллы для семей и компаний",
    fr: "Villas pour familles et groupes",
    it: "Ville per famiglie e gruppi",
    de: "Villen für Familien und Gruppen",
    uk: "Вілли для сімей та компаній",
  },
  revistaSpread3Text: {
    eng: "Spacious villas with multiple bedrooms, kitchens and outdoor areas. Ideal for longer stays and family holidays in Calpe.",
    esp: "Villas amplias con varios dormitorios, cocinas y zonas exteriores. Ideales para estancias largas y vacaciones en familia en Calpe.",
    ru: "Просторные виллы с несколькими спальнями, кухнями и зонами на улице. Идеально для длительного отдыха и семейного отпуска в Кальпе.",
    fr: "Villas spacieuses avec plusieurs chambres, cuisines et espaces extérieurs. Idéal pour longs séjours et vacances en famille à Calpe.",
    it: "Ville spaziose con più camere da letto, cucine e spazi esterni. Ideali per soggiorni lunghi e vacanze in famiglia a Calpe.",
    de: "Geräumige Villen mit mehreren Schlafzimmern, Küchen und Außenbereichen. Ideal für längere Aufenthalte und Familienurlaub in Calpe.",
    uk: "Просторні вілли з кількома спальнями, кухнями та зонами на вулиці. Ідеально для тривалого відпочинку та сімейного відпустку в Кальпе.",
  },
  revHeroLabel: { eng: "Inspiration & News", esp: "Inspiración y Noticias", ru: "Вдохновение и новости", fr: "Inspiration et actualités", it: "Ispirazione e notizie", de: "Inspiration & Nachrichten", uk: "Натхнення та новини" },
  revHeroTitle: { eng: "INFTOUR Magazine", esp: "Revista INFTOUR", ru: "Журнал INFTOUR", fr: "Magazine INFTOUR", it: "Rivista INFTOUR", de: "INFTOUR Magazin", uk: "Журнал INFTOUR" },
  revHeroDesc: {
    eng: "Discover the Costa Blanca through our lifestyle articles, guides and exclusive tips.",
    esp: "Descubra la Costa Blanca a través de nuestros artículos de estilo de vida, guías y consejos exclusivos.",
    ru: "Откройте для себя Коста-Бланку в наших статьях о стиле жизни, гидах и эксклюзивных советах.",
    fr: "Découvrez la Costa Blanca à travers nos articles lifestyle, guides et conseils exclusifs.",
    it: "Scopri la Costa Blanca attraverso i nostri articoli lifestyle, guide e consigli esclusivi.",
    de: "Entdecken Sie die Costa Blanca durch unsere Lifestyle-Artikel, Guides und exklusive Tipps.",
    uk: "Відкрийте для себе Коста-Бланку в наших статтях про стиль життя, гідах та ексклюзивних порадах.",
  },
  revFeaturedLabel: { eng: "Destination guide", esp: "Guía de Destino", ru: "Путеводитель", fr: "Guide de destination", it: "Guida di destinazione", de: "Reiseführer", uk: "Путівник" },
  revFeaturedTitle: { eng: "Holidays in Calpe: The Definitive Guide", esp: "Vacaciones en Calpe: La Guía Definitiva", ru: "Отдых в Кальпе: Полный гид", fr: "Vacances à Calpe : le guide définitif", it: "Vacanze a Calpe: la guida definitiva", de: "Urlaub in Calpe: der definitive Guide", uk: "Відпочинок у Кальпе: Повний гід" },
  revFeaturedDesc: {
    eng: "Planning the perfect Mediterranean holiday means knowing the best-kept secrets. From the majestic Peñón de Ifach to the fine sandy beaches.",
    esp: "Planificar unas vacaciones perfectas en el Mediterráneo requiere conocer los secretos mejor guardados. Desde el majestuoso Peñón de Ifach hasta las playas de arena fina.",
    ru: "Планировать идеальный отдых на Средиземноморье — значит знать лучшие секреты. От величественного Пеньон-де-Ифач до пляжей с мелким песком.",
    fr: "Planifier des vacances parfaites en Méditerranée, c'est connaître les secrets les mieux gardés. Du majestueux Peñón de Ifach aux plages de sable fin.",
    it: "Pianificare una vacanza perfetta nel Mediterraneo significa conoscere i segreti meglio custoditi. Dal maestoso Peñón de Ifach alle spiagge di sabbia fine.",
    de: "Die perfekte Mittelmeer-Reise planen heißt, die bestgehüteten Geheimnisse zu kennen. Vom majestätischen Peñón de Ifach bis zu den feinen Sandstränden.",
    uk: "Планувати ідеальну відпустку на Середземному морі — значить знати найкращі секрети. Від величного Пеньйон-де-Іфач до пляжів з дрібним піском.",
  },
  revLatestTitle: { eng: "Latest articles", esp: "Últimos Artículos", ru: "Последние статьи", fr: "Derniers articles", it: "Ultimi articoli", de: "Neueste Artikel", uk: "Останні статті" },
  revArticle1Tag: { eng: "Nature", esp: "Naturaleza", ru: "Природа", fr: "Nature", it: "Natura", de: "Natur", uk: "Природа" },
  revArticle1Title: { eng: "The 5 most secret coves", esp: "Las 5 Calas más secretas", ru: "5 самых укромных бухт", fr: "Les 5 calanques les plus secrètes", it: "Le 5 calette più segrete", de: "Die 5 geheimsten Buchten", uk: "5 найзатишніших бухт" },
  revArticle1Desc: {
    eng: "Escape the crowds. Discover paradise corners of crystal-clear waters ideal for snorkelling.",
    esp: "Escápese de las multitudes. Descubra rincones paradisíacos de aguas cristalinas ideales para hacer snorkel.",
    ru: "Уйдите от толп. Откройте райские уголки с кристально чистой водой для снорклинга.",
    fr: "Échappez à la foule. Découvrez des coins paradisiaques aux eaux cristallines idéales pour le snorkeling.",
    it: "Scappa dalla folla. Scopri angoli paradisiaci con acque cristalline ideali per lo snorkeling.",
    de: "Entfliehen Sie den Menschenmassen. Entdecken Sie Paradiese mit kristallklarem Wasser zum Schnorcheln.",
    uk: "Утечіть від натовпу. Відкрийте райські куточки з кришталево чистою водою для снорклінгу.",
  },
  revArticle2Tag: { eng: "Gastronomy", esp: "Gastronomía", ru: "Гастрономия", fr: "Gastronomie", it: "Gastronomia", de: "Gastronomie", uk: "Гастрономія" },
  revArticle2Title: { eng: "Where to eat Arròs del Senyoret", esp: "Dónde comer el Arròs del Senyoret", ru: "Где попробовать Arròs del Senyoret", fr: "Où déguster l'Arròs del Senyoret", it: "Dove mangiare l'Arròs del Senyoret", de: "Wo man Arròs del Senyoret isst", uk: "Де скуштувати Arròs del Senyoret" },
  revArticle2Desc: {
    eng: "A gastronomic route through the best restaurants in Calpe harbour.",
    esp: "Una ruta gastronómica por los mejores restaurantes del puerto de Calpe.",
    ru: "Гастрономический маршрут по лучшим ресторанам порта Кальпе.",
    fr: "Une route gastronomique à travers les meilleurs restaurants du port de Calpe.",
    it: "Un percorso gastronomico tra i migliori ristoranti del porto di Calpe.",
    de: "Eine kulinarische Route durch die besten Restaurants im Hafen von Calpe.",
    uk: "Гастрономічний маршрут по найкращих ресторанах порту Кальпе.",
  },
  revLiveTitle: { eng: "Live: Calpe", esp: "En Directo: Calpe", ru: "В эфире: Кальпе", fr: "En direct : Calpe", it: "In diretta: Calpe", de: "Live: Calpe", uk: "В ефірі: Кальпе" },
  revLive1Title: { eng: "Calpe renews its Blue Flags", esp: "Calpe renueva sus Banderas Azules", ru: "Кальпе продлевает Голубые флаги", fr: "Calpe renouvelle ses Pavillons Bleus", it: "Calpe rinnova le Bandiere Blu", de: "Calpe erneuert seine Blauen Flaggen", uk: "Кальпе продовжує Сині прапори" },
  revLive1Desc: {
    eng: "Arenal-Bol and La Fossa beaches keep their international award for excellent water quality.",
    esp: "Las playas de Arenal-Bol y La Fossa mantienen su galardón internacional por la excelente calidad de sus aguas.",
    ru: "Пляжи Arenal-Bol и La Fossa сохраняют международную награду за отличное качество воды.",
    fr: "Les plages d'Arenal-Bol et La Fossa conservent leur distinction internationale pour l'excellente qualité de leurs eaux.",
    it: "Le spiagge di Arenal-Bol e La Fossa mantengono il riconoscimento internazionale per l'eccellente qualità delle acque.",
    de: "Die Strände Arenal-Bol und La Fossa behalten ihre internationale Auszeichnung für exzellente Wasserqualität.",
    uk: "Пляжі Arenal-Bol та La Fossa зберігають міжнародну нагороду за відмінну якість води.",
  },
  revLive2Title: { eng: "Moors and Christians Festival", esp: "Fiestas de Moros y Cristianos", ru: "Фестиваль мавров и христиан", fr: "Fêtes des Maures et Chrétiens", it: "Festa di Mori e Cristiani", de: "Mauren- und Christenfest", uk: "Фестиваль маврів і християн" },
  revLive2Desc: {
    eng: "Get ready for the most spectacular event of the year in Calpe.",
    esp: "Prepárese para el evento más espectacular del año en Calpe.",
    ru: "Подготовьтесь к самому зрелищному событию года в Кальпе.",
    fr: "Préparez-vous pour l'événement le plus spectaculaire de l'année à Calpe.",
    it: "Preparatevi per l'evento più spettacolare dell'anno a Calpe.",
    de: "Bereiten Sie sich auf das spektakulärste Event des Jahres in Calpe vor.",
    uk: "Підготуйтеся до найбільш видовищної події року в Кальпе.",
  },

  // Services
  servicesTitle: { eng: "Services", esp: "Servicios", ru: "Услуги", fr: "Services", it: "Servizi", de: "Dienstleistungen", uk: "Послуги" },
  svcHeroLabel: { eng: "Concierge Service", esp: "Servicio de Conserjería", ru: "Консьерж-сервис", fr: "Service Concierge", it: "Servizio Concierge", de: "Concierge-Service", uk: "Консьєрж-сервіс" },
  svcHeroTitle1: {
    eng: "We take care of the details.",
    esp: "Nosotros nos ocupamos de los detalles.",
    ru: "Мы занимаемся деталями.",
    fr: "Nous nous occupons des détails.",
    it: "Noi ci occupiamo dei dettagli.",
    de: "Wir kümmern uns um die Details.",
    uk: "Ми дбаємо про деталі.",
  },
  svcHeroTitle2: {
    eng: "You take home the experiences.",
    esp: "Usted se lleva las experiencias.",
    ru: "Вы забираете впечатления.",
    fr: "Vous repartez avec les expériences.",
    it: "Voi vi portate a casa le esperienze.",
    de: "Sie nehmen die Erlebnisse mit.",
    uk: "Ви забираєте враження з собою.",
  },
  svcHeroDesc: {
    eng: "Unlike a traditional booking, INFTOUR offers a level of attention and care comparable to a luxury cruise.",
    esp: "A diferencia de una reserva tradicional, INFTOUR ofrece un nivel de atención y cuidado comparable al de un crucero de lujo.",
    ru: "В отличие от обычного бронирования, INFTOUR предлагает уровень заботы и внимания, сравнимый с круизом класса люкс.",
    fr: "Contrairement à une réservation traditionnelle, INFTOUR offre un niveau d'attention et de soin comparable à une croisière de luxe.",
    it: "A differenza di una prenotazione tradizionale, INFTOUR offre un livello di attenzione e cura paragonabile a una crociera di lusso.",
    de: "Anders als eine traditionelle Buchung bietet INFTOUR ein Maß an Aufmerksamkeit und Betreuung vergleichbar mit einer Luxuskreuzfahrt.",
    uk: "На відміну від звичайного бронювання, INFTOUR пропонує рівень турботи та уваги, порівняний з круїзом класу люкс.",
  },
  svcCardAITitle: { eng: "AI Assistant", esp: "Asistente AI", ru: "ИИ-ассистент", fr: "Assistant IA", it: "Assistente IA", de: "KI-Assistent", uk: "ШІ-асистент" },
  svcCardAI1: { eng: "24/7 instant support", esp: "Soporte instantáneo 24/7", ru: "Мгновенная поддержка 24/7", fr: "Assistance instantanée 24h/24", it: "Supporto istantaneo 24/7", de: "Sofortige Unterstützung 24/7", uk: "Миттєва підтримка 24/7" },
  svcCardAI2: { eng: "Help with any incident", esp: "Asistencia ante cualquier incidencia", ru: "Помощь при любом инциденте", fr: "Assistance en cas d'incident", it: "Assistenza per qualsiasi evenienza", de: "Hilfe bei jedem Vorfall", uk: "Допомога з будь-яким інцидентом" },
  svcCardAI3: { eng: "Quick guide to local services", esp: "Guía rápida de servicios urbanos", ru: "Краткий гид по городским услугам", fr: "Guide rapide des services locaux", it: "Guida rapida ai servizi locali", de: "Kurzer Überblick über lokale Dienste", uk: "Короткий гід по міських послугах" },
  svcCardAI4: { eng: "Fluid support in your language", esp: "Atención fluida en su idioma", ru: "Поддержка на вашем языке", fr: "Prise en charge fluide dans votre langue", it: "Assistenza fluida nella tua lingua", de: "Unterstützung in Ihrer Sprache", uk: "Підтримка вашою мовою" },
  svcCardRefTitle: { eng: "Reference numbers", esp: "Números de Referencia", ru: "Справочные номера", fr: "Numéros de référence", it: "Numeri di riferimento", de: "Referenznummern", uk: "Довідкові номери" },
  svcCardRef1: { eng: "Emergency services", esp: "Servicios de emergencia", ru: "Экстренные службы", fr: "Services d'urgence", it: "Servizi di emergenza", de: "Notdienste", uk: "Екстрені служби" },
  svcCardRef2: { eng: "Medical / Pharmacy", esp: "Médico / Farmacia", ru: "Медицина / Аптека", fr: "Médecin / Pharmacie", it: "Medico / Farmacia", de: "Arzt / Apotheke", uk: "Медицина / Аптека" },
  svcCardRef3: { eng: "Transfer and car rental", esp: "Traslado y Alquiler de coches", ru: "Трансфер и аренда авто", fr: "Transfert et location de voiture", it: "Transfer e noleggio auto", de: "Transfer und Autovermietung", uk: "Трансфер та оренда авто" },
  svcCardRef4: { eng: "Tours / Activities", esp: "Excursiones / Actividades", ru: "Экскурсии / Активности", fr: "Excursions / Activités", it: "Escursioni / Attività", de: "Ausflüge / Aktivitäten", uk: "Екскурсії / Активності" },
  svcCardCleaningTitle: { eng: "Cleaning service", esp: "Servicio de Limpieza", ru: "Уборка", fr: "Service de ménage", it: "Servizio di pulizia", de: "Reinigungsservice", uk: "Прибирання" },
  svcCardCleaningDesc: {
    eng: "We maintain hotel standards with cleaning and sheet changes on request.",
    esp: "Mantenemos el estándar de un hotel con limpieza y cambio de sábanas bajo petición.",
    ru: "Поддерживаем гостиничные стандарты: уборка и смена белья по запросу.",
    fr: "Nous maintenons les standards hôteliers avec ménage et changement de draps sur demande.",
    it: "Manteniamo lo standard alberghiero con pulizia e cambio lenzuola su richiesta.",
    de: "Wir halten Hotelstandards mit Reinigung und Bettwäschewechsel auf Anfrage.",
    uk: "Підтримуємо готельні стандарти: прибирання та зміна білизни на запит.",
  },
  svcCardOfficeTitle: { eng: "Office in Calpe", esp: "Oficina en Calpe", ru: "Офис в Кальпе", fr: "Bureau à Calpe", it: "Ufficio a Calpe", de: "Büro in Calpe", uk: "Офіс у Кальпе" },
  svcCardOfficeDesc: {
    eng: "Unlike anonymous platforms, we are physically nearby to help you.",
    esp: "A diferencia de plataformas anónimas, estamos físicamente cerca para ayudarle.",
    ru: "В отличие от анонимных платформ, мы физически рядом, чтобы помочь.",
    fr: "Contrairement aux plateformes anonymes, nous sommes physiquement présents pour vous aider.",
    it: "A differenza delle piattaforme anonime, siamo fisicamente vicini per aiutarti.",
    de: "Anders als anonyme Plattformen sind wir physisch vor Ort, um Ihnen zu helfen.",
    uk: "На відміну від анонімних платформ, ми фізично поруч, щоб допомогти.",
  },
  servicesIntro: {
    eng: "What we offer for your stay in Calpe.",
    esp: "Qué ofrecemos para tu estancia en Calpe.",
    ru: "Что мы предлагаем для вашего отдыха в Кальпе.",
    fr: "Ce que nous proposons pour votre séjour à Calpe.",
    it: "Cosa offriamo per il tuo soggiorno a Calpe.",
    de: "Was wir für Ihren Aufenthalt in Calpe anbieten.",
    uk: "Що ми пропонуємо для вашого відпочинку в Кальпе.",
  },
  service1Title: {
    eng: "Exclusive apartment rentals",
    esp: "Alquiler exclusivo de apartamentos",
    ru: "Эксклюзивная аренда апартаментов",
    fr: "Location exclusive d'appartements",
    it: "Affitti esclusivi di appartamenti",
    de: "Exklusive Apartment-Vermietung",
    uk: "Ексклюзивна оренда апартаментів",
  },
  service1Desc: {
    eng: "Hand-picked apartments with sea views and hotel-level amenities. Each property is inspected and maintained to the highest standards, so you enjoy the privacy of a home with the comfort of a boutique stay.",
    esp: "Apartamentos seleccionados con vistas al mar y comodidades de nivel hotelero. Cada propiedad está inspeccionada y mantenida con los más altos estándares, para que disfrutes de la privacidad de un hogar con el confort de una estancia boutique.",
    ru: "Тщательно подобранные апартаменты с видом на море и уровнем комфорта отеля. Каждый объект проверен и содержится в идеальном состоянии — уединённость дома и комфорт бутик-отеля.",
    fr: "Appartements sélectionnés avec vue mer et confort de niveau hôtelier. Chaque bien est inspecté et entretenu selon les plus hauts standards.",
    it: "Appartamenti selezionati con vista mare e comfort da hotel. Ogni proprietà è ispezionata e mantenuta ai massimi standard.",
    de: "Ausgewählte Apartments mit Meerblick und Hotelkomfort. Jede Immobilie wird geprüft und nach höchsten Standards gepflegt.",
    uk: "Ретельно підібрані апартаменти з видом на море та рівнем комфорту готелю. Кожен об'єкт перевірений і підтримується в ідеальному стані.",
  },
  service2Title: {
    eng: "Concierge & experiences",
    esp: "Concierge y experiencias",
    ru: "Консьерж и впечатления",
    fr: "Concierge et expériences",
    it: "Concierge ed esperienze",
    de: "Concierge & Erlebnisse",
    uk: "Консьєрж та враження",
  },
  service2Desc: {
    eng: "From boat trips and wine tastings to guided hikes up the Peñón de Ifach—we organise activities tailored to you. Our team knows Calpe inside out and can suggest the best restaurants, beaches and hidden spots.",
    esp: "Desde paseos en barco y catas de vino hasta rutas guiadas por el Peñón de Ifach: organizamos actividades a tu medida. Nuestro equipo conoce Calpe al dedillo y puede recomendarte los mejores restaurantes, playas y rincones.",
    ru: "Морские прогулки, дегустации вин, экскурсии на Пеньон-де-Ифач — организуем активности под вас. Наша команда знает Кальпе как никто и подскажет лучшие рестораны, пляжи и укромные места.",
    fr: "De sorties en bateau et dégustations de vins aux randonnées guidées du Peñón de Ifach : nous organisons des activités sur mesure. Notre équipe connaît Calpe sur le bout des doigts.",
    it: "Da gite in barca e degustazioni di vini alle escursioni guidate sul Peñón de Ifach: organizziamo attività su misura. Il nostro team conosce Calpe a fondo.",
    de: "Von Bootsfahrten und Weinproben bis zu geführten Wanderungen auf den Peñón de Ifach – wir organisieren maßgeschneiderte Aktivitäten. Unser Team kennt Calpe in- und auswendig.",
    uk: "Морські прогулянки, дегустації вин, екскурсії на Пеньйон-де-Іфач — організуємо активності під вас. Наша команда знає Кальпе як ніхто.",
  },
  service3Title: {
    eng: "Support whenever you need it",
    esp: "Soporte cuando lo necesites",
    ru: "Поддержка в любое время",
    fr: "Assistance à tout moment",
    it: "Supporto quando serve",
    de: "Unterstützung rund um die Uhr",
    uk: "Підтримка в будь-який час",
  },
  service3Desc: {
    eng: "Clear check-in instructions, 24/7 contact for emergencies, and a dedicated point of contact for your stay. Book with confidence knowing we're here to make your trip smooth from arrival to departure.",
    esp: "Instrucciones claras de entrada, contacto 24/7 para emergencias y un interlocutor dedicado durante tu estancia. Reserva con confianza sabiendo que estamos aquí para que tu viaje sea perfecto de principio a fin.",
    ru: "Понятные инструкции по заезду, контакт 24/7 в случае срочных вопросов и персональный менеджер на время отдыха. Бронируйте с уверенностью — мы рядом от прилёта до отъезда.",
    fr: "Instructions d'arrivée claires, contact 24h/24 pour urgences et interlocuteur dédié. Réservez en toute confiance.",
    it: "Istruzioni di check-in chiare, contatto 24/7 per emergenze e referente dedicato. Prenota con fiducia.",
    de: "Klare Check-in-Anweisungen, 24/7-Notfallkontakt und fester Ansprechpartner. Buchen Sie mit Vertrauen.",
    uk: "Зрозумілі інструкції з заїзду, контакт 24/7 у разі термінових питань та персональний менеджер на час відпочинку.",
  },
  servicesPracticalTitle: {
    eng: "Practical information",
    esp: "Información práctica",
    ru: "Полезная информация",
    fr: "Informations pratiques",
    it: "Informazioni pratiche",
    de: "Praktische Informationen",
    uk: "Корисна інформація",
  },
  servicesPracticalIntro: {
    eng: "Useful contacts and services in Calpe.",
    esp: "Contactos y servicios útiles en Calpe.",
    ru: "Полезные контакты и услуги в Кальпе.",
    fr: "Contacts et services utiles à Calpe.",
    it: "Contatti e servizi utili a Calpe.",
    de: "Nützliche Kontakte und Dienste in Calpe.",
    uk: "Корисні контакти та послуги в Кальпе.",
  },
  practicalPolice: { eng: "Police & emergency", esp: "Policía y emergencias", ru: "Полиция и экстренные службы", fr: "Police et urgences", it: "Polizia e emergenze", de: "Polizei und Notfall", uk: "Поліція та екстрені служби" },
  practicalPoliceDetail: {
    eng: "Local police (Policía Local): 965 83 00 00. Guardia Civil: 965 83 02 00. Emergency (all): 112.",
    esp: "Policía Local: 965 83 00 00. Guardia Civil: 965 83 02 00. Emergencias: 112.",
    ru: "Полиция (Policía Local): 965 83 00 00. Гражданская гвардия: 965 83 02 00. Экстренная служба: 112.",
    fr: "Police locale : 965 83 00 00. Guardia Civil : 965 83 02 00. Urgences : 112.",
    it: "Polizia locale: 965 83 00 00. Guardia Civil: 965 83 02 00. Emergenze: 112.",
    de: "Lokalpolizei: 965 83 00 00. Guardia Civil: 965 83 02 00. Notfall: 112.",
    uk: "Місцева поліція: 965 83 00 00. Гвардія Цивіль: 965 83 02 00. Екстрена служба: 112.",
  },
  practicalMedical: { eng: "Medical & pharmacies", esp: "Médico y farmacias", ru: "Медицина и аптеки", fr: "Médecine et pharmacies", it: "Medico e farmacie", de: "Medizin und Apotheken", uk: "Медицина та аптеки" },
  practicalMedicalDetail: {
    eng: "Health centre (Centro de Salud): 965 83 02 50. 24h pharmacy rotation; check farmaciasdeguardia.com. Emergency: 112.",
    esp: "Centro de Salud: 965 83 02 50. Farmacias de guardia 24h; consulta farmaciasdeguardia.com. Emergencias: 112.",
    ru: "Медцентр (Centro de Salud): 965 83 02 50. Дежурные аптеки 24ч: farmaciasdeguardia.com. Экстренная служба: 112.",
    fr: "Centre de santé : 965 83 02 50. Pharmacies de garde 24h : farmaciasdeguardia.com. Urgences : 112.",
    it: "Centro di salute: 965 83 02 50. Farmacie di turno 24h: farmaciasdeguardia.com. Emergenze: 112.",
    de: "Gesundheitszentrum: 965 83 02 50. Notdienst-Apotheken 24h: farmaciasdeguardia.com. Notfall: 112.",
    uk: "Медцентр: 965 83 02 50. Чергові аптеки 24 год: farmaciasdeguardia.com. Екстрена служба: 112.",
  },
  practicalTransfers: { eng: "Airport transfers", esp: "Traslados al aeropuerto", ru: "Трансфер в аэропорт", fr: "Transferts aéroport", it: "Transfer aeroporto", de: "Flughafentransfer", uk: "Трансфер в аеропорт" },
  practicalTransfersDetail: {
    eng: "Private and shared transfers to/from Alicante and Valencia airports. We can arrange pickup and drop-off for your stay.",
    esp: "Traslados privados y compartidos a/desde aeropuertos de Alicante y Valencia. Podemos gestionar recogida y regreso.",
    ru: "Индивидуальные и групповые трансферы в аэропорты Аликанте и Валенсии. Можем организовать встречу и проводы.",
    fr: "Transferts privés et partagés vers/depuis les aéroports d'Alicante et Valence. Nous pouvons organiser prise en charge et retour.",
    it: "Transfer privati e condivisi da/per aeroporti di Alicante e Valencia. Possiamo organizzare ritiro e rientro.",
    de: "Private und gemeinsame Transfers zu/von den Flughäfen Alicante und Valencia. Abholung und Rückfahrt auf Anfrage.",
    uk: "Індивідуальні та групові трансфери в аеропорти Аліканте та Валенсії. Можемо організувати зустріч та проводи.",
  },
  practicalCarRental: { eng: "Car rental", esp: "Alquiler de coches", ru: "Аренда авто", fr: "Location de voitures", it: "Noleggio auto", de: "Autovermietung", uk: "Оренда авто" },
  practicalCarRentalDetail: {
    eng: "Several agencies in Calpe and at Alicante airport. We recommend booking in advance in high season.",
    esp: "Varias agencias en Calpe y en el aeropuerto de Alicante. Recomendamos reservar con antelación en temporada alta.",
    ru: "Агентства в Кальпе и в аэропорту Аликанте. В высокий сезон лучше бронировать заранее.",
    fr: "Plusieurs agences à Calpe et à l'aéroport d'Alicante. Nous recommandons de réserver à l'avance en haute saison.",
    it: "Diverse agenzie a Calpe e all'aeroporto di Alicante. Consigliamo di prenotare in anticipo in alta stagione.",
    de: "Mehrere Vermieter in Calpe und am Flughafen Alicante. Wir empfehlen Vorausbuchung in der Hochsaison.",
    uk: "Агентства в Кальпе та в аеропорту Аліканте. У високий сезон краще бронювати заздалегідь.",
  },
  practicalSupermarket: { eng: "Supermarket delivery", esp: "Supermercado a domicilio", ru: "Доставка продуктов", fr: "Livraison supermarché", it: "Consegna supermercato", de: "Supermarkt-Lieferung", uk: "Доставка продуктів" },
  practicalSupermarketDetail: {
    eng: "Supermarkets that deliver to your door: Consum, Mercadona, Carrefour and others offer online orders with delivery to Calpe.",
    esp: "Supermercados con entrega a domicilio: Consum, Mercadona, Carrefour y otros ofrecen pedidos online con entrega en Calpe.",
    ru: "Доставка на дом: Consum, Mercadona, Carrefour и другие доставляют заказы в Кальпе.",
    fr: "Supermarchés livrant à domicile : Consum, Mercadona, Carrefour et autres. Commandes en ligne avec livraison à Calpe.",
    it: "Supermercati con consegna a domicilio: Consum, Mercadona, Carrefour e altri. Ordini online con consegna a Calpe.",
    de: "Supermärkte mit Lieferung: Consum, Mercadona, Carrefour u.a. bieten Online-Bestellung mit Lieferung nach Calpe.",
    uk: "Доставка на дім: Consum, Mercadona, Carrefour та інші доставляють замовлення в Кальпе.",
  },
  practicalBikeRental: { eng: "Bike rental", esp: "Alquiler de bicis", ru: "Аренда велосипедов", fr: "Location de vélos", it: "Noleggio bici", de: "Fahrradverleih", uk: "Оренда велосипедів" },
  practicalBikeRentalDetail: {
    eng: "Bike and e-bike rental in Calpe for exploring the coast and Peñón area. Ask us for recommended providers.",
    esp: "Alquiler de bicis y e-bikes en Calpe para explorar la costa y el Peñón. Pregúntanos por proveedores recomendados.",
    ru: "Аренда велосипедов и электросамокатов в Кальпе для поездок по побережью и к Пеньону. Подскажем проверенных прокатчиков.",
    fr: "Location de vélos et vélos électriques à Calpe pour explorer la côte et le Peñón. Demandez-nous les prestataires recommandés.",
    it: "Noleggio bici e e-bike a Calpe per esplorare la costa e il Peñón. Chiedici i fornitori consigliati.",
    de: "Fahrrad- und E-Bike-Verleih in Calpe für Küste und Peñón. Wir nennen Ihnen empfehlenswerte Anbieter.",
    uk: "Оренда велосипедів та електросамокатів у Кальпе для поїздок узбережжям та до Пеньйону. Підкажемо перевірених прокатників.",
  },
  servicesActivitiesTitle: {
    eng: "Activities",
    esp: "Actividades",
    ru: "Активности",
    fr: "Activités",
    it: "Attività",
    de: "Aktivitäten",
    uk: "Активності",
  },
  servicesActivitiesIntro: {
    eng: "Ideas for your stay: hiking, sea, culture and more.",
    esp: "Ideas para tu estancia: senderismo, mar, cultura y más.",
    ru: "Идеи для отдыха: пешие походы, море, культура и не только.",
    fr: "Idées pour votre séjour : randonnée, mer, culture et plus.",
    it: "Idee per il tuo soggiorno: trekking, mare, cultura e altro.",
    de: "Ideen für Ihren Aufenthalt: Wandern, Meer, Kultur und mehr.",
    uk: "Ідеї для відпочинку: піші походи, море, культура та інше.",
  },
  activityHiking: { eng: "Hiking", esp: "Senderismo", ru: "Пешие походы", fr: "Randonnée", it: "Trekking", de: "Wandern", uk: "Піші походи" },
  activityHikingDesc: {
    eng: "Peñón de Ifach natural park, coastal paths and marked routes. Stunning views and varied difficulty levels.",
    esp: "Parque natural del Peñón de Ifach, sendas costeras y rutas señalizadas. Vistas increíbles y distintos niveles de dificultad.",
    ru: "Природный парк Пеньон-де-Ифач, прибрежные тропы и маркированные маршруты. Красивейшие виды и разная сложность.",
    fr: "Parc naturel du Peñón de Ifach, sentiers côtiers et itinéraires balisés. Vues magnifiques et niveaux variés.",
    it: "Parco naturale del Peñón de Ifach, sentieri costieri e percorsi segnalati. Viste mozzafiato e livelli di difficoltà vari.",
    de: "Naturpark Peñón de Ifach, Küstenwege und markierte Routen. Atemberaubende Aussichten und verschiedene Schwierigkeitsgrade.",
    uk: "Природний парк Пеньйон-де-Іфач, прибережні стежки та марковані маршрути. Чудові види та різна складність.",
  },
  activityBoating: { eng: "Boating & sea", esp: "Barca y mar", ru: "Морские прогулки", fr: "Bateau et mer", it: "Barca e mare", de: "Boot & Meer", uk: "Морські прогулянки" },
  activityBoatingDesc: {
    eng: "Boat trips, kayak, paddle and sailing. Explore the coast and coves from the water.",
    esp: "Paseos en barco, kayak, paddle y vela. Explora la costa y las calas desde el mar.",
    ru: "Прогулки на катере, каякинг, SUP и парус. Исследуйте побережье и бухты с воды.",
    fr: "Sorties en bateau, kayak, paddle et voile. Explorez la côte et les criques depuis l'eau.",
    it: "Gite in barca, kayak, paddle e vela. Esplora la costa e le calette dall'acqua.",
    de: "Bootsfahrten, Kajak, Paddeln und Segeln. Erkunden Sie die Küste und Buchten vom Wasser aus.",
    uk: "Прогулянки на катері, каякінг, SUP та вітрило. Досліджуйте узбережжя та бухти з води.",
  },
  activityDiving: { eng: "Diving & snorkelling", esp: "Buceo y snorkel", ru: "Дайвинг и снорклинг", fr: "Plongée et snorkeling", it: "Sub e snorkeling", de: "Tauchen & Schnorcheln", uk: "Дайвінг та снорклінг" },
  activityDivingDesc: {
    eng: "Diving schools and snorkelling spots along the coast. Clear waters and marine life.",
    esp: "Escuelas de buceo y zonas de snorkel en la costa. Aguas transparentes y vida marina.",
    ru: "Дайв-школы и места для снорклинга. Прозрачная вода и подводный мир.",
    fr: "Écoles de plongée et spots de snorkeling sur la côte. Eaux claires et vie marine.",
    it: "Scuole sub e spot per lo snorkeling lungo la costa. Acque limpide e vita marina.",
    de: "Tauchschulen und Schnorchelspots an der Küste. Klares Wasser und marine Lebenswelt.",
    uk: "Дайв-школи та місця для снорклінгу. Прозора вода та підводний світ.",
  },
  activityCycling: { eng: "Cycling", esp: "Ciclismo", ru: "Велоспорт", fr: "Vélo", it: "Ciclismo", de: "Radfahren", uk: "Велоспорт" },
  activityCyclingDesc: {
    eng: "Road and mountain biking. Calpe is a popular base for cyclists; routes for all levels.",
    esp: "Ciclismo en carretera y montaña. Calpe es base ideal para ciclistas; rutas para todos los niveles.",
    ru: "Шоссе и маунтинбайк. Кальпе — популярная база для велосипедистов; маршруты на любой уровень.",
    fr: "Vélo route et VTT. Calpe est une base populaire pour les cyclistes ; circuits pour tous niveaux.",
    it: "Ciclismo su strada e mountain bike. Calpe è base ideale per ciclisti; percorsi per tutti i livelli.",
    de: "Straßen- und Mountainbiken. Calpe ist eine beliebte Basis für Radfahrer; Routen für alle Levels.",
    uk: "Шосе та маунтинбайк. Кальпе — популярна база для велосипедистів; маршрути на будь-який рівень.",
  },
  activityWine: { eng: "Wine & gastronomy", esp: "Vino y gastronomía", ru: "Вина и гастрономия", fr: "Vin et gastronomie", it: "Vino e gastronomia", de: "Wein & Gastronomie", uk: "Вино та гастрономія" },
  activityWineDesc: {
    eng: "Wine tastings, local bodegas and restaurants. Costa Blanca wines and Mediterranean cuisine.",
    esp: "Catas de vino, bodegas y restaurantes de la zona. Vinos de la Costa Blanca y cocina mediterránea.",
    ru: "Дегустации вин, местные бодеги и рестораны. Вина Коста-Бланки и средиземноморская кухня.",
    fr: "Dégustations de vins, bodegas et restaurants locaux. Vins de la Costa Blanca et cuisine méditerranéenne.",
    it: "Degustazioni di vino, bodeghe e ristoranti locali. Vini della Costa Blanca e cucina mediterranea.",
    de: "Weinproben, lokale Bodegas und Restaurants. Costa-Blanca-Weine und mediterrane Küche.",
    uk: "Дегустації вин, місцеві бодеги та ресторани. Вина Коста-Бланки та середземноморська кухня.",
  },
  activityBeach: { eng: "Beaches & family", esp: "Playas y familia", ru: "Пляжи и семья", fr: "Plages et famille", it: "Spiagge e famiglia", de: "Strände & Familie", uk: "Пляжі та сім'я" },
  activityBeachDesc: {
    eng: "Sandy and rocky beaches, promenades and family-friendly activities. Calpe has something for everyone.",
    esp: "Playas de arena y roca, paseos marítimos y actividades familiares. Calpe tiene algo para todos.",
    ru: "Песчаные и скалистые пляжи, набережные и семейный отдых. В Кальпе есть всё для каждого.",
    fr: "Plages de sable et de roche, promenades et activités familiales. Calpe a de quoi plaire à tous.",
    it: "Spiagge di sabbia e roccia, passeggiate e attività per famiglie. Calpe ha qualcosa per tutti.",
    de: "Sand- und Felsstrände, Promenaden und familienfreundliche Aktivitäten. Calpe hat für jeden etwas.",
    uk: "Піщані та скелясті пляжі, набережні та сімейний відпочинок. У Кальпе є все для кожного.",
  },

  // Lobby
  lobbyTitle: { eng: "Lobby", esp: "Lobby", ru: "Лобби", fr: "Lobby", it: "Lobby", de: "Lobby", uk: "Лобі" },
  sectionRealEstate: {
    eng: "About us",
    esp: "Sobre nosotros",
    ru: "О компании",
    fr: "À propos",
    it: "Chi siamo",
    de: "Über uns",
    uk: "Про нас",
  },
  sectionRealEstateContent: {
    eng: "INFTOUR is a licensed tour operator offering exclusive apartment rentals in Calpe. We provide a hotel-level service with the privacy of your own home, in one of the most iconic locations on the Costa Blanca—at the foot of the Peñón de Ifach.",
    esp: "INFTOUR es un tour operador con licencia que ofrece alquiler exclusivo de apartamentos en Calpe. Servicio de nivel hotelero con la privacidad de tu hogar, en uno de los enclaves más emblemáticos de la Costa Blanca, a los pies del Peñón de Ifach.",
    ru: "INFTOUR — лицензированный туроператор, эксклюзивная аренда апартаментов в Кальпе. Сервис уровня отеля и уединённость собственного дома у подножия Пеньон-де-Ифач на Коста-Бланке.",
    fr: "INFTOUR est un tour-opérateur agréé proposant des locations d'appartements exclusives à Calpe. Service de niveau hôtelier avec l'intimité de chez vous, au pied du Peñón de Ifach sur la Costa Blanca.",
    it: "INFTOUR è un tour operator autorizzato che offre affitti esclusivi di appartamenti a Calpe. Servizio di livello alberghiero con la privacy di casa, ai piedi del Peñón de Ifach sulla Costa Blanca.",
    de: "INFTOUR ist ein lizenzierter Reiseveranstalter mit exklusiven Apartment-Vermietungen in Calpe. Hotelkomfort mit der Privatsphäre des eigenen Zuhauses am Fuße des Peñón de Ifach an der Costa Blanca.",
    uk: "INFTOUR — ліцензований туроператор, ексклюзивна оренда апартаментів у Кальпе. Сервіс рівня готелю та затишок власного дому біля підніжжя Пеньйон-де-Іфач на Коста-Бланці.",
  },
  lobbyTeamHeading: {
    eng: "Our team",
    esp: "Nuestro equipo",
    ru: "Наша команда",
    fr: "Notre équipe",
    it: "Il nostro team",
    de: "Unser Team",
    uk: "Наша команда",
  },
  team1Name: { eng: "Alex García", esp: "Alex García", ru: "Алекс Гарсия", fr: "Alex García", it: "Alex García", de: "Alex García", uk: "Алекс Гарсія" },
  team1Title: { eng: "Managing Director", esp: "Director general", ru: "Генеральный директор", fr: "Directeur général", it: "Direttore generale", de: "Geschäftsführer", uk: "Генеральний директор" },
  team2Name: { eng: "Maria López", esp: "María López", ru: "Мария Лопес", fr: "Maria López", it: "Maria López", de: "Maria López", uk: "Марія Лопес" },
  team2Title: { eng: "Operations & Guest Experience", esp: "Operaciones y experiencia del huésped", ru: "Операции и работа с гостями", fr: "Opérations et expérience client", it: "Operazioni e esperienza ospiti", de: "Betrieb & Gästebetreuung", uk: "Операції та робота з гостями" },
  team3Name: { eng: "Carlos Ruiz", esp: "Carlos Ruiz", ru: "Карлос Руис", fr: "Carlos Ruiz", it: "Carlos Ruiz", de: "Carlos Ruiz", uk: "Карлос Руїс" },
  team3Title: { eng: "Property & Partnerships", esp: "Propiedades y alianzas", ru: "Недвижимость и партнёрства", fr: "Biens et partenariats", it: "Immobili e partnership", de: "Immobilien & Partnerschaften", uk: "Нерухомість та партнерства" },
  team4Name: { eng: "Elena Martínez", esp: "Elena Martínez", ru: "Елена Мартинес", fr: "Elena Martínez", it: "Elena Martínez", de: "Elena Martínez", uk: "Олена Мартінес" },
  team4Title: { eng: "Marketing & Reservations", esp: "Marketing y reservas", ru: "Маркетинг и бронирования", fr: "Marketing et réservations", it: "Marketing e prenotazioni", de: "Marketing & Buchungen", uk: "Маркетинг та бронювання" },
  lobbyOfficeHeading: {
    eng: "Our office",
    esp: "Nuestra oficina",
    ru: "Наш офис",
    fr: "Notre bureau",
    it: "Il nostro ufficio",
    de: "Unser Büro",
    uk: "Наш офіс",
  },
  lobbyOpenInMaps: {
    eng: "Open in Google Maps",
    esp: "Abrir en Google Maps",
    ru: "Открыть в Google Картах",
    fr: "Ouvrir dans Google Maps",
    it: "Apri in Google Maps",
    de: "In Google Maps öffnen",
    uk: "Відкрити в Google Картах",
  },
  sectionAIChat: {
    eng: "What the AI assistant can do",
    esp: "Qué puede hacer el asistente IA",
    ru: "Возможности ИИ-ассистента",
    fr: "Ce que l'assistant IA peut faire",
    it: "Cosa può fare l'assistente IA",
    de: "Was der KI-Assistent kann",
    uk: "Можливості ШІ-асистента",
  },
  sectionAIChatContent: {
    eng: "Our AI assistant can help you with: booking enquiries and availability, information about experiences and activities in Calpe, recommendations for restaurants and sights, and general questions about your stay. Open the chat from the menu to get started.",
    esp: "Nuestro asistente IA puede ayudarte con: consultas de reserva y disponibilidad, información sobre experiencias y actividades en Calpe, recomendaciones de restaurantes y lugares de interés, y preguntas generales sobre tu estancia. Abre el chat desde el menú para empezar.",
    ru: "ИИ-ассистент подскажет: по бронированию и наличию, по впечатлениям и активностям в Кальпе, по ресторанам и достопримечательностям, по общим вопросам отдыха. Откройте чат в меню, чтобы начать.",
    fr: "Notre assistant IA peut vous aider pour : demandes de réservation et disponibilité, infos sur les expériences et activités à Calpe, recommandations restaurants et visites, questions générales. Ouvrez le chat depuis le menu.",
    it: "Il nostro assistente IA può aiutarti con: richieste di prenotazione e disponibilità, informazioni su esperienze e attività a Calpe, consigli su ristoranti e luoghi, domande generali. Apri la chat dal menu.",
    de: "Unser KI-Assistent hilft bei: Buchungsanfragen und Verfügbarkeit, Infos zu Erlebnissen und Aktivitäten in Calpe, Restaurant- und Sehenswürdigkeits-Empfehlungen, allgemeinen Fragen. Chat im Menü öffnen.",
    uk: "ШІ-асистент підкаже: з бронювання та наявності, з вражень та активностей у Кальпе, з ресторанів та пам'яток, з загальних питань відпочинку. Відкрийте чат у меню.",
  },
  sectionContact: {
    eng: "Contact us",
    esp: "Contáctanos",
    ru: "Написать нам",
    fr: "Contactez-nous",
    it: "Contattaci",
    de: "Kontakt",
    uk: "Написати нам",
  },
  sectionContactSubtitle: {
    eng: "Have a question or want to book? We usually reply within 24 hours.",
    esp: "¿Tienes una pregunta o quieres reservar? Solemos responder en 24 horas.",
    ru: "Вопрос или бронирование? Обычно отвечаем в течение 24 часов.",
    fr: "Une question ou une réservation ? Nous répondons généralement sous 24 h.",
    it: "Hai una domanda o vuoi prenotare? Di solito rispondiamo entro 24 ore.",
    de: "Frage oder Buchungswunsch? Wir antworten in der Regel innerhalb von 24 Stunden.",
    uk: "Питання чи бронювання? Зазвичай відповідаємо протягом 24 годин.",
  },
  formEmailLabel: { eng: "Your email", esp: "Tu email", ru: "Ваш email", fr: "Votre email", it: "La tua email", de: "Ihre E-Mail", uk: "Ваш email" },
  formEmailPlaceholder: { eng: "name@example.com", esp: "nombre@ejemplo.com", ru: "nombre@ejemplo.com", fr: "nom@exemple.com", it: "nome@esempio.com", de: "name@beispiel.de", uk: "ім'я@приклад.com" },
  formMessageLabel: { eng: "Message", esp: "Mensaje", ru: "Сообщение", fr: "Message", it: "Messaggio", de: "Nachricht", uk: "Повідомлення" },
  formMessagePlaceholder: {
    eng: "Tell us about your dates, group size or any question...",
    esp: "Cuéntanos fechas, número de personas o tu pregunta...",
    ru: "Даты, количество гостей или ваш вопрос...",
    fr: "Indiquez vos dates, nombre de personnes ou votre question...",
    it: "Indica date, numero di persone o la tua domanda...",
    de: "Daten, Gästeanzahl oder Ihre Frage...",
    uk: "Дати, кількість гостей або ваше питання...",
  },
  formSubmit: { eng: "Send message", esp: "Enviar mensaje", ru: "Отправить сообщение", fr: "Envoyer le message", it: "Invia messaggio", de: "Nachricht senden", uk: "Надіслати повідомлення" },
  formSendsTo: {
    eng: "Replies go to your email. We'll copy booking@inftour.com.",
    esp: "Las respuestas irán a tu email. Nosotros recibimos en booking@inftour.com.",
    ru: "Ответ придёт на ваш email. Мы получим копию на booking@inftour.com.",
    fr: "Les réponses iront à votre email. Nous recevrons une copie sur booking@inftour.com.",
    it: "Le risposte andranno alla tua email. Noi riceviamo su booking@inftour.com.",
    de: "Antworten gehen an Ihre E-Mail. Wir erhalten eine Kopie an booking@inftour.com.",
    uk: "Відповідь надійде на ваш email. Ми отримаємо копію на booking@inftour.com.",
  },
  formSuccess: {
    eng: "Thank you. We will reply soon.",
    esp: "Gracias. Te responderemos pronto.",
    ru: "Спасибо. Мы ответим в ближайшее время.",
    fr: "Merci. Nous répondrons bientôt.",
    it: "Grazie. Risponderemo presto.",
    de: "Danke. Wir werden bald antworten.",
    uk: "Дякуємо. Ми відповімо найближчим часом.",
  },
  formError: {
    eng: "Something went wrong. Please try again.",
    esp: "Algo salió mal. Inténtalo de nuevo.",
    ru: "Произошла ошибка. Попробуйте ещё раз.",
    fr: "Une erreur s'est produite. Veuillez réessayer.",
    it: "Qualcosa è andato storto. Riprova.",
    de: "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    uk: "Щось пішло не так. Спробуйте ще раз.",
  },
  sectionPolicies: {
    eng: "Policies & legal",
    esp: "Políticas y legal",
    ru: "Политики и условия",
    fr: "Politiques et légal",
    it: "Politiche e legale",
    de: "Richtlinien & Rechtliches",
    uk: "Політики та умови",
  },
  cancellationPolicy: {
    eng: "Cancellation policy",
    esp: "Política de cancelación",
    ru: "Политика отмены",
    fr: "Politique d'annulation",
    it: "Politica di cancellazione",
    de: "Stornobedingungen",
    uk: "Політика скасування",
  },
  paymentPolicy: {
    eng: "Payment",
    esp: "Pago",
    ru: "Оплата",
    fr: "Paiement",
    it: "Pagamento",
    de: "Zahlung",
    uk: "Оплата",
  },
  termsPolicy: {
    eng: "Terms & conditions",
    esp: "Términos y condiciones",
    ru: "Условия",
    fr: "Conditions générales",
    it: "Termini e condizioni",
    de: "AGB",
    uk: "Умови",
  },
  sectionFaq: { eng: "FAQ", esp: "Preguntas frecuentes", ru: "Частые вопросы", fr: "FAQ", it: "Domande frequenti", de: "FAQ", uk: "Часті питання" },
  faq1Q: {
    eng: "What is the check-in time?",
    esp: "¿Cuál es la hora de entrada?",
    ru: "Во сколько заезд?",
    fr: "Quelle est l'heure d'arrivée ?",
    it: "Qual è l'orario di check-in?",
    de: "Wann ist der Check-in?",
    uk: "О котрій заїзд?",
  },
  faq1A: {
    eng: "Check-in is from 16:00. Check-out is by 11:00.",
    esp: "La entrada es desde las 16:00. La salida es hasta las 11:00.",
    ru: "Заезд с 16:00, выезд до 11:00.",
    fr: "Arrivée à partir de 16h. Départ avant 11h.",
    it: "Check-in dalle 16:00. Check-out entro le 11:00.",
    de: "Check-in ab 16:00 Uhr. Check-out bis 11:00 Uhr.",
    uk: "Заїзд з 16:00, виїзд до 11:00.",
  },
  faq2Q: {
    eng: "Is there parking?",
    esp: "¿Hay parking?",
    ru: "Есть ли парковка?",
    fr: "Y a-t-il un parking ?",
    it: "C'è parcheggio?",
    de: "Gibt es Parkplätze?",
    uk: "Чи є парковка?",
  },
  faq2A: {
    eng: "Parking options depend on the property. Details are in your booking confirmation.",
    esp: "Las opciones de parking dependen de la propiedad. Los detalles están en tu confirmación de reserva.",
    ru: "Зависит от объекта. Подробности указаны в подтверждении брони.",
    fr: "Les options de parking dépendent du bien. Les détails sont dans votre confirmation de réservation.",
    it: "Le opzioni di parcheggio dipendono dalla proprietà. I dettagli sono nella conferma di prenotazione.",
    de: "Parkmöglichkeiten hängen von der Immobilie ab. Details stehen in Ihrer Buchungsbestätigung.",
    uk: "Залежить від об'єкта. Подробиці в підтвердженні бронювання.",
  },
  faq3Q: {
    eng: "How can I modify or cancel my booking?",
    esp: "¿Cómo puedo modificar o cancelar mi reserva?",
    ru: "Как изменить или отменить бронирование?",
    fr: "Comment modifier ou annuler ma réservation ?",
    it: "Come posso modificare o cancellare la prenotazione?",
    de: "Wie kann ich meine Buchung ändern oder stornieren?",
    uk: "Як змінити або скасувати бронювання?",
  },
  faq3A: {
    eng: "Contact us by email or through the AI chat. We will assist you according to our cancellation policy.",
    esp: "Contáctanos por email o por el chat IA. Te ayudaremos según nuestra política de cancelación.",
    ru: "Напишите нам на email или в ИИ-чат. Мы поможем согласно политике отмены.",
    fr: "Contactez-nous par email ou via le chat IA. Nous vous aiderons selon notre politique d'annulation.",
    it: "Contattaci per email o tramite chat IA. Ti assisteremo secondo la nostra politica di cancellazione.",
    de: "Kontaktieren Sie uns per E-Mail oder über den KI-Chat. Wir helfen Ihnen gemäß unserer Stornobedingungen.",
    uk: "Напишіть нам на email або в ШІ-чат. Допоможемо згідно з політикою скасування.",
  },

  // Lobby page (ejemplos/lobby.html)
  lobHeroLabel: { eng: "Virtual Reception", esp: "Recepción Virtual", ru: "Виртуальная рецепция", fr: "Réception virtuelle", it: "Reception virtuale", de: "Virtuelle Rezeption", uk: "Віртуальна рецепція" },
  lobHeroTitle: { eng: "Welcome to the Lobby", esp: "Bienvenido al Lobby", ru: "Добро пожаловать в лобби", fr: "Bienvenue au Lobby", it: "Benvenuto nella Lobby", de: "Willkommen in der Lobby", uk: "Ласкаво просимо до лобі" },
  lobHeroDesc: {
    eng: "Your information and assistance centre. Here you will find everything you need to know about us, our policies and how to act in any situation.",
    esp: "Su centro de información y asistencia. Aquí encontrará todo lo que necesita saber sobre nosotros, nuestras políticas y cómo actuar ante cualquier situación.",
    ru: "Ваш центр информации и помощи. Здесь вы найдёте всё о нас, наших правилах и действиях в любой ситуации.",
    fr: "Votre centre d'information et d'assistance. Vous y trouverez tout ce qu'il faut savoir sur nous, nos politiques et comment agir en toute situation.",
    it: "Il vostro centro di informazione e assistenza. Qui troverete tutto quello che serve su di noi, le nostre politiche e come agire in ogni situazione.",
    de: "Ihr Informations- und Assistenzzentrum. Hier finden Sie alles über uns, unsere Richtlinien und das Verhalten in jeder Situation.",
    uk: "Ваш центр інформації та допомоги. Тут ви знайдете все про нас, наші політики та дії в будь-якій ситуації.",
  },
  lobAboutTitle: { eng: "About us", esp: "Sobre Nosotros", ru: "О нас", fr: "À propos de nous", it: "Chi siamo", de: "Über uns", uk: "Про нас" },
  lobAboutIntro: {
    eng: "INFTOUR is a boutique holiday rental agency in Calpe. We combine the privacy of an exclusive apartment with the service standards of a premium hotel.",
    esp: "INFTOUR es una agencia boutique de alquiler vacacional en Calpe. Combinamos la privacidad de un apartamento exclusivo con los estándares de servicio de un hotel premium.",
    ru: "INFTOUR — бутиковое агентство аренды в Кальпе. Мы сочетаем уединённость эксклюзивного апартамента со стандартами сервиса премиум-отеля.",
    fr: "INFTOUR est une agence boutique de location vacances à Calpe. Nous allions l'intimité d'un appartement exclusif aux standards de service d'un hôtel premium.",
    it: "INFTOUR è un'agenzia boutique di affitti per le vacanze a Calpe. Uniamo la privacy di un appartamento esclusivo agli standard di servizio di un hotel premium.",
    de: "INFTOUR ist eine Boutique-Ferienvermietungsagentur in Calpe. Wir verbinden die Privatsphäre einer exklusiven Ferienwohnung mit dem Service eines Premium-Hotels.",
    uk: "INFTOUR — бутикове агентство оренди в Кальпе. Ми поєднуємо затишок ексклюзивного апартаменту зі стандартами сервісу преміум-готелю.",
  },
  lobAboutReadMore: { eng: "Read our full story", esp: "Leer nuestra historia completa", ru: "Прочитать нашу историю", fr: "Lire notre histoire complète", it: "Leggi la nostra storia completa", de: "Unsere vollständige Geschichte lesen", uk: "Прочитати нашу історію" },
  lobAboutStory1: {
    eng: "Founded with the aim of raising the standard of accommodation on the Costa Blanca, INFTOUR manages a carefully curated collection of first-line properties. We are not an aggregator; we are direct managers focused on quality, not quantity.",
    esp: "Fundada con el objetivo de elevar el estándar del alojamiento en la Costa Blanca, INFTOUR gestiona una cuidada colección de propiedades de primera línea. No somos un agregador; somos gestores directos enfocados en la calidad, no en la cantidad.",
    ru: "Созданная с целью повысить уровень размещения на Коста-Бланке, INFTOUR управляет тщательно подобранной коллекцией объектов. Мы не агрегатор; мы прямые управляющие, ориентированные на качество.",
    fr: "Fondée pour élever le standard de l'hébergement sur la Costa Blanca, INFTOUR gère une collection soigneusement sélectionnée de propriétés de premier ordre. Nous ne sommes pas un agrégateur ; nous sommes des gestionnaires directs axés sur la qualité.",
    it: "Fondata con l'obiettivo di elevare lo standard dell'alloggio sulla Costa Blanca, INFTOUR gestisce una collezione curata di proprietà di prima linea. Non siamo un aggregatore; siamo gestori diretti focalizzati sulla qualità.",
    de: "Mit dem Ziel gegründet, den Standard der Unterkünfte an der Costa Blanca zu heben, verwaltet INFTOUR eine sorgfältig kuratierte Sammlung erstklassiger Objekte. Wir sind kein Aggregator; wir sind direkte Verwalter mit Fokus auf Qualität.",
    uk: "Заснована з метою підвищити рівень проживання на Коста-Бланці, INFTOUR керує ретельно підібраною колекцією об'єктів. Ми не агрегатор; ми прямі управителі, орієнтовані на якість.",
  },
  lobAboutStory2: {
    eng: "Our philosophy is based on 'Concierge Service': we believe that true luxury lies in peace of mind. That is why we have physical offices in the heart of Calpe and a team dedicated to making your stay an unforgettable experience.",
    esp: "Nuestra filosofía se basa en el 'Concierge Service': creemos que el verdadero lujo reside en la tranquilidad. Por ello, contamos con oficinas físicas en el corazón de Calpe y un equipo dedicado a hacer de su estancia una experiencia inolvidable.",
    ru: "Наша философия — «Concierge Service»: мы верим, что настоящая роскошь — это спокойствие. Поэтому у нас есть офис в центре Кальпе и команда, которая сделает ваш отдых незабываемым.",
    fr: "Notre philosophie repose sur le 'Concierge Service' : nous croyons que le vrai luxe réside dans la tranquillité d'esprit. C'est pourquoi nous avons des bureaux physiques au cœur de Calpe et une équipe dévouée à rendre votre séjour inoubliable.",
    it: "La nostra filosofia si basa sul 'Concierge Service': crediamo che il vero lusso risieda nella tranquillità. Per questo abbiamo uffici fisici nel cuore di Calpe e un team dedicato a rendere il vostro soggiorno indimenticabile.",
    de: "Unsere Philosophie basiert auf 'Concierge Service': Wir glauben, dass wahrer Luxus in der Ruhe des Geistes liegt. Daher haben wir Büros im Herzen von Calpe und ein Team, das Ihren Aufenthalt unvergesslich macht.",
    uk: "Наша філософія — «Concierge Service»: ми віримо, що справжня розкіш — це спокій. Тому у нас є офіс у центрі Кальпе та команда, яка зробить ваш відпочинок незабутнім.",
  },
  lobAITitle: { eng: "Your AI Assistant", esp: "Tu Asistente AI", ru: "Ваш ИИ-ассистент", fr: "Votre assistant IA", it: "Il tuo assistente IA", de: "Ihr KI-Assistent", uk: "Ваш ШІ-асистент" },
  lobAI1: { eng: "24/7 instant support", esp: "Soporte instantáneo 24/7", ru: "Мгновенная поддержка 24/7", fr: "Support instantané 24h/24", it: "Supporto istantaneo 24/7", de: "24/7 Sofort-Support", uk: "Миттєва підтримка 24/7" },
  lobAI2: { eng: "Help with any issue during your stay", esp: "Asistencia ante cualquier incidencia durante su estancia", ru: "Помощь при любом инциденте во время проживания", fr: "Assistance pour tout incident pendant votre séjour", it: "Assistenza per qualsiasi evenienza durante il soggiorno", de: "Hilfe bei jedem Vorfall während Ihres Aufenthalts", uk: "Допомога при будь-якому інциденті під час проживання" },
  lobAI3: { eng: "Quick guide to urban services and concierge", esp: "Guía rápida de servicios urbanos y conserjería", ru: "Краткий гид по городским услугам и консьержу", fr: "Guide rapide des services urbains et de la conciergerie", it: "Guida rapida ai servizi urbani e alla concierge", de: "Schnellführer zu städtischen Diensten und Concierge", uk: "Короткий гід по міських послугах та консьєржу" },
  lobAI4: { eng: "Support in your native language", esp: "Atención fluida en su idioma nativo", ru: "Поддержка на вашем родном языке", fr: "Prise en charge fluide dans votre langue", it: "Assistenza fluida nella vostra lingua", de: "Unterstützung in Ihrer Muttersprache", uk: "Підтримка рідною мовою" },
  lobAIStartChat: { eng: "Start chat", esp: "Iniciar Chat", ru: "Начать чат", fr: "Démarrer le chat", it: "Avvia chat", de: "Chat starten", uk: "Почати чат" },
  lobContactWeAreHere: { eng: "We are here to help you", esp: "Estamos aquí para ayudarle", ru: "Мы здесь, чтобы помочь", fr: "Nous sommes là pour vous aider", it: "Siamo qui per aiutarti", de: "Wir sind für Sie da", uk: "Ми тут, щоб допомогти" },
  formNamePlaceholder: { eng: "Name", esp: "Nombre", ru: "Имя", fr: "Nom", it: "Nome", de: "Name", uk: "Ім'я" },
  lobFormHelpPlaceholder: { eng: "How can we help you?", esp: "¿En qué podemos ayudarle?", ru: "Чем мы можем помочь?", fr: "Comment pouvons-nous vous aider ?", it: "Come possiamo aiutarti?", de: "Wie können wir Ihnen helfen?", uk: "Чим ми можемо допомогти?" },
  lobAddressLine: { eng: "c. Jardin 3 Local INFTOUR, Calpe", esp: "c. Jardin 3 Local INFTOUR, Calpe", ru: "c. Jardin 3 Local INFTOUR, Кальпе", fr: "c. Jardin 3 Local INFTOUR, Calpe", it: "c. Jardin 3 Local INFTOUR, Calpe", de: "c. Jardin 3 Local INFTOUR, Calpe", uk: "c. Jardin 3 Local INFTOUR, Кальпе" },
  lobPhoneLine: { eng: "+34 600 000 000", esp: "+34 600 000 000", ru: "+34 600 000 000", fr: "+34 600 000 000", it: "+34 600 000 000", de: "+34 600 000 000", uk: "+34 600 000 000" },
  lobEmailLine: { eng: "mail@inftour.net", esp: "mail@inftour.net", ru: "mail@inftour.net", fr: "mail@inftour.net", it: "mail@inftour.net", de: "mail@inftour.net", uk: "mail@inftour.net" },
  lobInstructionsTitle: { eng: "Instructions: What to do if...?", esp: "Instrucciones: ¿Qué hacer si...?", ru: "Инструкции: Что делать, если...?", fr: "Instructions : Que faire si... ?", it: "Istruzioni: Cosa fare se...?", de: "Anweisungen: Was tun, wenn...?", uk: "Інструкції: Що робити, якщо...?" },
  lobInstr1Q: { eng: "...I have a medical emergency?", esp: "...tengo una emergencia médica?", ru: "...у меня медицинская чрезвычайная ситуация?", fr: "...j'ai une urgence médicale ?", it: "...ho un'emergenza medica?", de: "...ich einen medizinischen Notfall habe?", uk: "...у мене медична надзвичайна ситуація?" },
  lobInstr1A: {
    eng: "Call 112 immediately for emergencies. You can find the nearest on-duty pharmacy or health centre in the 'Reference numbers' section of our AI Assistant.",
    esp: "Llame inmediatamente al 112 para emergencias. Puede encontrar la farmacia de guardia más cercana o el centro de salud en la sección de 'Números de Referencia' de nuestro Asistente AI.",
    ru: "Немедленно звоните 112. Ближайшую дежурную аптеку или медцентр можно найти в разделе «Справочные номера» у нашего ИИ-ассистента.",
    fr: "Appelez le 112 immédiatement pour les urgences. Vous trouverez la pharmacie de garde ou le centre de santé le plus proche dans la section 'Numéros de référence' de notre assistant IA.",
    it: "Chiamate immediatamente il 112 per le emergenze. Potete trovare la farmacia di turno o il centro di salute nella sezione 'Numeri di riferimento' del nostro assistente IA.",
    de: "Rufen Sie sofort 112 für Notfälle an. Die nächste Notdienst-Apotheke oder das Gesundheitszentrum finden Sie im Abschnitt 'Referenznummern' unseres KI-Assistenten.",
    uk: "Негайно телефонуйте 112. Найближчу чергову аптеку або медцентр можна знайти в розділі «Довідкові номери» у нашого ШІ-асистента.",
  },
  lobInstr2Q: { eng: "...I lose the apartment keys?", esp: "...pierdo las llaves del apartamento?", ru: "...я потерял ключи от апартаментов?", fr: "...je perds les clés de l'appartement ?", it: "...perdo le chiavi dell'appartamento?", de: "...ich den Wohnungsschlüssel verliere?", uk: "...я загубив ключі від апартаментів?" },
  lobInstr2A: {
    eng: "Contact our support team immediately via the on-call number. Key replacement may incur an additional charge according to the booking terms.",
    esp: "Contacte con nuestro equipo de soporte inmediatamente a través del número de guardia. La reposición de llaves puede conllevar un cargo adicional según los términos de reserva.",
    ru: "Немедленно свяжитесь с нашей службой поддержки по номеру дежурного. Замена ключей может быть платной согласно условиям бронирования.",
    fr: "Contactez notre équipe d'assistance immédiatement via le numéro de garde. Le remplacement des clés peut entraîner des frais supplémentaires selon les conditions de réservation.",
    it: "Contattate immediatamente il nostro team di supporto tramite il numero di guardia. La sostituzione delle chiavi può comportare un costo aggiuntivo secondo i termini di prenotazione.",
    de: "Kontaktieren Sie sofort unser Support-Team über die Rufbereitschaft. Der Schlüsselaustausch kann laut Buchungsbedingungen zusätzliche Kosten verursachen.",
    uk: "Негайно зв'яжіться з нашою підтримкою за номером чергового. Заміна ключів може бути платною згідно з умовами бронювання.",
  },
  lobInstr3Q: { eng: "...I need a late check-out?", esp: "...necesito un Late Check-out?", ru: "...мне нужен поздний выезд?", fr: "...j'ai besoin d'un check-out tardif ?", it: "...ho bisogno di un check-out tardivo?", de: "...ich einen späten Check-out brauche?", uk: "...мені потрібен пізній виїзд?" },
  lobInstr3A: {
    eng: "Standard check-out is at 11:00 AM. If you need to extend your stay by a few hours, contact our office one day in advance. It is subject to availability and possible supplements.",
    esp: "El check-out estándar es a las 11:00 AM. Si necesita extender su estancia unas horas, contacte con nuestra oficina un día antes. Estará sujeto a disponibilidad y posibles suplementos.",
    ru: "Стандартный выезд до 11:00. Если нужно продлить пребывание на несколько часов, свяжитесь с офисом за день. Возможность зависит от наличия и может быть платной.",
    fr: "Le check-out standard est à 11h. Si vous devez prolonger votre séjour de quelques heures, contactez notre bureau la veille. Sous réserve de disponibilité et suppléments éventuels.",
    it: "Il check-out standard è alle 11:00. Se dovete prolungare il soggiorno di qualche ora, contattate il nostro ufficio il giorno prima. È soggetto a disponibilità e possibili supplementi.",
    de: "Der Standard-Check-out ist um 11:00 Uhr. Wenn Sie Ihren Aufenthalt um einige Stunden verlängern möchten, kontaktieren Sie unser Büro einen Tag im Voraus. Abhängig von Verfügbarkeit und möglichen Zuschlägen.",
    uk: "Стандартний виїзд до 11:00. Якщо потрібно продовжити перебування на кілька годин, зв'яжіться з офісом за день. Можливість залежить від наявності та може бути платною.",
  },
  lobInstr4Q: { eng: "...something in the apartment doesn't work?", esp: "...algo no funciona en el apartamento?", ru: "...что-то в апартаментах не работает?", fr: "...quelque chose ne fonctionne pas dans l'appartement ?", it: "...qualcosa non funziona nell'appartamento?", de: "...etwas in der Wohnung nicht funktioniert?", uk: "...щось в апартаментах не працює?" },
  lobInstr4A: {
    eng: "Message our concierge WhatsApp describing the problem. Our maintenance team will attend as soon as possible to resolve the issue without disrupting your holiday.",
    esp: "Escriba a nuestro WhatsApp de conserjería detallando el problema. Nuestro equipo de mantenimiento acudirá lo antes posible para resolver la incidencia sin interrumpir sus vacaciones.",
    ru: "Напишите в WhatsApp консьержа с описанием проблемы. Наша служба обслуживания приедет как можно скорее, чтобы решить вопрос без нарушения вашего отдыха.",
    fr: "Écrivez à notre WhatsApp conciergerie en décrivant le problème. Notre équipe de maintenance interviendra dès que possible pour résoudre le problème sans perturber vos vacances.",
    it: "Scrivete al nostro WhatsApp della concierge descrivendo il problema. Il nostro team di manutenzione interverrà il prima possibile per risolvere il problema senza disturbare le vostre vacanze.",
    de: "Schreiben Sie unserem Concierge-WhatsApp mit einer Beschreibung des Problems. Unser Wartungsteam wird sich so schnell wie möglich kümmern, ohne Ihren Urlaub zu stören.",
    uk: "Напишіть у WhatsApp консьєржа з описом проблеми. Наша служба обслуговування приїде якомога швидше, щоб вирішити питання без порушення вашого відпочинку.",
  },
  lobPoliciesTitle: { eng: "Policies and privacy", esp: "Políticas y Privacidad", ru: "Политики и конфиденциальность", fr: "Politiques et confidentialité", it: "Politiche e privacy", de: "Richtlinien und Datenschutz", uk: "Політики та конфіденційність" },
  cancellationPolicyDesc: {
    eng: "Refund conditions and free cancellation deadlines.",
    esp: "Conozca las condiciones de reembolso y plazos de cancelación gratuita.",
    ru: "Условия возврата и сроки бесплатной отмены.",
    fr: "Conditions de remboursement et délais d'annulation gratuite.",
    it: "Condizioni di rimborso e termini di cancellazione gratuita.",
    de: "Rückerstattungsbedingungen und Fristen für kostenlose Stornierung.",
    uk: "Умови повернення та терміни безкоштовного скасування.",
  },
  paymentPolicyDesc: {
    eng: "Information on deposits, accepted cards and secure payments.",
    esp: "Información sobre depósitos, tarjetas aceptadas y pagos seguros.",
    ru: "Информация о депозитах, принимаемых картах и безопасной оплате.",
    fr: "Informations sur les acomptes, cartes acceptées et paiements sécurisés.",
    it: "Informazioni su depositi, carte accettate e pagamenti sicuri.",
    de: "Informationen zu Anzahlungen, akzeptierten Karten und sicheren Zahlungen.",
    uk: "Інформація про депозити, прийнятні картки та безпечна оплата.",
  },
  termsPolicyDesc: {
    eng: "House rules, deposits and guest responsibilities.",
    esp: "Reglas de la casa, fianzas y responsabilidades del huésped.",
    ru: "Правила дома, залоги и обязанности гостя.",
    fr: "Règlement de la maison, cautions et responsabilités des voyageurs.",
    it: "Regole della casa, cauzioni e responsabilità dell'ospite.",
    de: "Hausregeln, Kautionen und Gästepflichten.",
    uk: "Правила будинку, застави та обов'язки гостя.",
  },
  privacyPolicyDesc: {
    eng: "How we protect your data and handle your personal information.",
    esp: "Cómo protegemos sus datos y manejamos su información personal.",
    ru: "Как мы защищаем ваши данные и обрабатываем персональную информацию.",
    fr: "Comment nous protégeons vos données et gérons vos informations personnelles.",
    it: "Come proteggiamo i vostri dati e gestiamo le vostre informazioni personali.",
    de: "Wie wir Ihre Daten schützen und mit Ihren personenbezogenen Daten umgehen.",
    uk: "Як ми захищаємо ваші дані та обробляємо персональну інформацію.",
  },
};

type LangStore = {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: keyof typeof translations, params?: Record<string, string | number>) => string;
};

function persistLang(lang: Lang) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(STORAGE_KEY, lang);
  } catch (e) {
    console.warn("Failed to persist language:", e);
  }
}

export const useLangStore = create<LangStore>((set, get) => ({
  lang: "eng",

  setLang: (lang) => {
    set({ lang });
    persistLang(lang);
    if (typeof document !== "undefined") {
      document.documentElement.lang = LANG_TO_HTML[lang];
    }
  },

  t: (key: string, params?: Record<string, string | number>) => {
    const { lang } = get();
    const entry = translations[key as keyof typeof translations];
    if (!entry) return key;
    let text = (entry as LangStrings)[lang] ?? entry.eng;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
      });
    }
    return text;
  },
}));

export function restoreLastLanguage(): Lang {
  if (typeof window === "undefined") return "eng";
  try {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved && VALID_LANGS.includes(saved as Lang)) {
      const lang = saved as Lang;
      useLangStore.setState({ lang });
      if (typeof document !== "undefined") {
        document.documentElement.lang = LANG_TO_HTML[lang];
      }
      return lang;
    }
    // No saved preference: use browser language and persist it
    const detected = getBrowserLang();
    useLangStore.setState({ lang: detected });
    if (typeof document !== "undefined") {
      document.documentElement.lang = LANG_TO_HTML[detected];
    }
    persistLang(detected);
    return detected;
  } catch (e) {
    console.warn("Failed to restore language:", e);
  }
  return "eng";
}
