export type ModalSeoPage = {
  slug: string;
  title: string;
  description: string;
  parentPath: string;
  componentName: string;
};

export const modalSeoPages: ModalSeoPage[] = [
  {
    slug: "footer-raicv",
    title: "RAICV information | INFTOUR",
    description: "Regulatory and RAICV details shown in the INFTOUR footer modal.",
    parentPath: "/",
    componentName: "FooterRaicvModal",
  },
  {
    slug: "reserva-gallery",
    title: "Property gallery | INFTOUR",
    description: "Image gallery content displayed in the direct booking gallery modal.",
    parentPath: "/reserva-directa-v2",
    componentName: "GalleryModal",
  },
  {
    slug: "reserva-property-details",
    title: "Property details | INFTOUR",
    description: "Detailed property information shown in the direct booking property modal.",
    parentPath: "/reserva-directa-v2",
    componentName: "PropertyModal",
  },
  {
    slug: "experiencias-restaurants",
    title: "Experiencias: Restaurants | INFTOUR",
    description: "Restaurant recommendations content from the Experiencias restaurants modal.",
    parentPath: "/experiencias",
    componentName: "RestaurantsModal",
  },
  {
    slug: "experiencias-markets",
    title: "Experiencias: Markets | INFTOUR",
    description: "Local markets content from the Experiencias markets modal.",
    parentPath: "/experiencias",
    componentName: "MarketsModal",
  },
  {
    slug: "experiencias-recipes",
    title: "Experiencias: Recipes | INFTOUR",
    description: "Traditional recipes and gastronomy content from the Experiencias recipes modal.",
    parentPath: "/experiencias",
    componentName: "RecipesModal",
  },
  {
    slug: "experiencias-sport-renting",
    title: "Experiencias: Sport renting | INFTOUR",
    description: "Sport and renting activities from the Experiencias sport renting modal.",
    parentPath: "/experiencias",
    componentName: "SportRentingModal",
  },
  {
    slug: "experiencias-cycling",
    title: "Experiencias: Cycling | INFTOUR",
    description: "Cycling routes and recommendations from the Experiencias cycling modal.",
    parentPath: "/experiencias",
    componentName: "CyclingModal",
  },
  {
    slug: "experiencias-bbq-parks",
    title: "Experiencias: BBQ parks | INFTOUR",
    description: "Family barbecue and park content from the Experiencias BBQ parks modal.",
    parentPath: "/experiencias",
    componentName: "BBQParksModal",
  },
  {
    slug: "experiencias-feria",
    title: "Experiencias: Feria | INFTOUR",
    description: "Events and fair-related content from the Experiencias feria modal.",
    parentPath: "/experiencias",
    componentName: "FeriaModal",
  },
  {
    slug: "experiencias-calpe-grandeza",
    title: "Experiencias: Calpe grandeza | INFTOUR",
    description: "Calpe heritage and family content from the Experiencias Calpe grandeza modal.",
    parentPath: "/experiencias",
    componentName: "CalpeGrandezaModal",
  },
  {
    slug: "experiencias-parques-atracciones",
    title: "Experiencias: Parques de atracciones | INFTOUR",
    description: "Theme parks and family attractions from the Experiencias attractions modal.",
    parentPath: "/experiencias",
    componentName: "ParquesAtraccionesModal",
  },
  {
    slug: "experiencias-ecosistema-deportivo",
    title: "Experiencias: Ecosistema deportivo | INFTOUR",
    description: "Sports ecosystem content from the Experiencias sports ecosystem modal.",
    parentPath: "/experiencias",
    componentName: "EcosistemaDeportivoModal",
  },
  {
    slug: "experiencias-relax",
    title: "Experiencias: Relax | INFTOUR",
    description: "Relaxation and wellness content from the Experiencias relax modal.",
    parentPath: "/experiencias",
    componentName: "RelaxModal",
  },
  {
    slug: "experiencias-ifach",
    title: "Experiencias: Ifach | INFTOUR",
    description: "Penon de Ifach nature content from the Experiencias Ifach modal.",
    parentPath: "/experiencias",
    componentName: "IfachModal",
  },
  {
    slug: "experiencias-horizontes-marinos",
    title: "Experiencias: Horizontes marinos | INFTOUR",
    description: "Sea and coastal perspectives from the Experiencias Horizontes Marinos modal.",
    parentPath: "/experiencias",
    componentName: "HorizontesMarinosModal",
  },
  {
    slug: "experiencias-salinas",
    title: "Experiencias: Salinas | INFTOUR",
    description: "Salinas and natural landscape content from the Experiencias salinas modal.",
    parentPath: "/experiencias",
    componentName: "SalinasModal",
  },
  {
    slug: "services-reference-numbers",
    title: "Services: Reference numbers | INFTOUR",
    description: "Reference numbers and utility contacts shown in the services reference modal.",
    parentPath: "/services",
    componentName: "ReferenceNumbersModal",
  },
  {
    slug: "services-our-services",
    title: "Services: Our services | INFTOUR",
    description: "Operational and guest support services content from the our services modal.",
    parentPath: "/services",
    componentName: "OurServicesModal",
  },
  {
    slug: "services-requests-comments",
    title: "Services: Requests and comments | INFTOUR",
    description: "Requests and comments workflow content from the corresponding services modal.",
    parentPath: "/services",
    componentName: "RequestsCommentsModal",
  },
  {
    slug: "services-recipes-style",
    title: "Services: Recipes style | INFTOUR",
    description: "Recipes-style service content from the service recipes style modal component.",
    parentPath: "/services",
    componentName: "ServiceRecipesStyleModal",
  },
  {
    slug: "lobby-privacy",
    title: "Lobby: Privacy policy | INFTOUR",
    description: "Privacy policy information shown in the lobby privacy modal.",
    parentPath: "/lobby",
    componentName: "PrivacyModal",
  },
  {
    slug: "lobby-arrival-stay",
    title: "Lobby: Arrival and stay | INFTOUR",
    description: "Arrival and stay instructions from the lobby arrival/stay modal.",
    parentPath: "/lobby",
    componentName: "ArrivalStayModal",
  },
  {
    slug: "lobby-faq",
    title: "Lobby: FAQ | INFTOUR",
    description: "Frequently asked questions content from the lobby FAQ modal.",
    parentPath: "/lobby",
    componentName: "FaqModal",
  },
  {
    slug: "lobby-reporting-channel",
    title: "Lobby: Reporting channel | INFTOUR",
    description: "Reporting channel policy and process from the lobby reporting modal.",
    parentPath: "/lobby",
    componentName: "ReportingChannelModal",
  },
  {
    slug: "revista-pdf-viewer",
    title: "Revista: PDF viewer | INFTOUR",
    description: "Magazine PDF viewing modal used in the INFTOUR revista section.",
    parentPath: "/revista",
    componentName: "PdfModal",
  },
];
