type LangStrings = {
  eng: string;
  esp: string;
  ru: string;
  fr: string;
  it: string;
  de: string;
  uk: string;
  pl: string;
};

/** Parks & family picnic areas modal — content aligned with Áreas de BBQ y Parques (ES source). */
export const bbqParksModalTranslations: Record<string, LangStrings> = {
  expBBQParksModalTitle: {
    eng: "The aesthetics of rest in nature: Parks and family picnic areas in Calpe",
    esp: "Estética del descanso en la naturaleza: Parques y zonas para pícnics familiares en Calpe",
    ru: "Эстетика отдыха на природе: Парки и зоны для семейных пикников в Кальпе",
    fr: "L'esthétique du repos dans la nature : Parcs et aires de pique-nique familiales à Calpe",
    it: "L'estetica del riposo nella natura: Parchi e aree picnic per famiglie a Calpe",
    de: "Die Ästhetik der Ruhe in der Natur: Parks und Familien-Picknickzonen in Calpe",
    uk: "Естетика відпочинку на природі: Парки та зони для сімейних пікніків у Кальпе",
    pl: "Estetyka wypoczynku na łonie natury: Parki i miejsca na rodzinne pikniki w Calpe",
  },
  expBBQParksModalSubtitle: {
    eng: "The art of beautiful contrasts and Mediterranean hedonism in the shade of ancient trees",
    esp: "El arte de los hermosos contrastes y el hedonismo mediterráneo a la sombra de árboles centenarios",
    ru: "Искусство красивых контрастов и средиземноморского гедонизма в тени вековых деревьев",
    fr: "L'art des beaux contrastes et de l'hédonisme méditerranéen à l'ombre d'arbres centenaires",
    it: "L'arte dei bei contrasti e dell'edonismo mediterraneo all'ombra di alberi secolari",
    de: "Die Kunst schöner Kontraste und mediterranen Hedonismus im Schatten jahrhundertealter Bäume",
    uk: "Мистецтво красивих контрастів і середземноморського гедонізму в тіні столітніх дерев",
    pl: "Sztuka pięknych kontrastów i śródziemnomorskiego hedonizmu w cieniu starych drzew",
  },
  expBBQParksModalIntro: {
    eng: "True holidays on the Costa Blanca are not limited to sun loungers by the sea. Sometimes true luxury means swapping the beach for the deep shade of ancient trees, breathing in the scent of sun-warmed pine and sharing time with your loved ones. Calpe hides several green oases where resting in nature becomes a beautiful family ritual.",
    esp: "Las verdaderas vacaciones en la Costa Blanca no se limitan a las tumbonas a la orilla del mar. A veces, el verdadero lujo consiste en cambiar la playa por la densa sombra de árboles centenarios, respirar el aroma a pino calentado por el sol y compartir el tiempo con los suyos. Calpe esconde varios oasis verdes donde el descanso en la naturaleza se convierte en un hermoso ritual familiar.",
    ru: "Настоящий отдых на Коста-Бланке не ограничивается шезлонгами у моря. Иногда настоящая роскошь — это сменить пляж на густую тень вековых деревьев, вдохнуть аромат согретой солнцем сосны и провести время с близкими. В Кальпе есть несколько зелёных оазисов, где отдых на природе становится красивым семейным ритуалом.",
    fr: "Les vraies vacances sur la Costa Blanca ne se limitent pas aux transats au bord de la mer. Parfois, le vrai luxe, c'est quitter la plage pour l'ombre dense d'arbres centenaires, respirer le parfum du pin chauffé par le soleil et partager du temps avec les vôtres. Calpe recèle plusieurs oasis vertes où le repos dans la nature devient un beau rituel familial.",
    it: "Le vere vacanze sulla Costa Blanca non si limitano alle sdraio in riva al mare. A volte il vero lusso è scambiare la spiaggia con l'ombra fitta di alberi secolari, respirare il profumo del pino riscaldato dal sole e condividere il tempo con i propri cari. Calpe nasconde diverse oasi verdi dove il riposo nella natura diventa un bel rituale di famiglia.",
    de: "Echter Urlaub an der Costa Blanca beschränkt sich nicht auf Liegen am Meer. Manchmal bedeutet wahrer Luxus, den Strand gegen den tiefen Schatten uralter Bäume zu tauschen, den Duft sonnengewärmter Kiefern einzuatmen und Zeit mit den Liebsten zu teilen. Calpe birgt mehrere grüne Oasen, wo die Ruhe in der Natur zu einem schönen Familienritual wird.",
    uk: "Справжній відпочинок на Коста-Бланці не обмежується шезлонгами біля моря. Іноді справжня розкіш — це обміняти пляж на густу тінь столітніх дерев, вдихнути аромат сосни, прогрітої сонцем, і провести час із рідними. У Кальпе є кілька зелених оаз, де відпочинок на природі стає красивим сімейним ритуалом.",
    pl: "Prawdziwe wakacje na Costa Blanca to nie tylko leżaki nad morzem. Czasem prawdziwy luksus to zamiana plaży na gęsty cień starych drzew, zapach nagrzanego słońcem sosny i wspólny czas z bliskimi. Calpe kryje kilka zielonych oaz, gdzie odpoczynek w naturze staje się pięknym rodzinnym rytuałem.",
  },
  expBBQParksModalSection1: {
    eng: "1. Parque de la Vallesa: Comfort and eucalyptus groves\nIf you seek the perfect balance between wild nature and comfort, head to Parque de la Vallesa. It is a green space carefully sheltered by Mediterranean pines and eucalypts. Here you will find sturdy wooden tables and welcoming paths: an impeccable spot for a long meal where children can play freely while adults enjoy a glass of intense Monastrell red wine.\nAtmosphere: Serenity, family warmth and the aesthetic of a woodland picnic.\nAddress: Carrer de la Vallesa, 03710 Calp, Alicante.",
    esp: "1. Parque de la Vallesa: Confort y bosques de eucaliptos\nSi busca el equilibrio perfecto entre la naturaleza virgen y el confort, diríjase al Parque de la Vallesa. Es una zona verde cuidadosamente resguardada por las copas de los pinos mediterráneos y eucaliptos. Aquí encontrará robustas mesas de madera y acogedores senderos: un lugar impecable para una comida prolongada, donde los niños pueden jugar libremente mientras los adultos disfrutan de una copa de vino tinto intenso de la uva Monastrell.\nAtmósfera: Serenidad, calidez familiar y la estética de un pícnic en el bosque.\nDirección: Carrer de la Vallesa, 03710 Calp, Alicante.",
    ru: "1. Парк Ла-Вальеса: Комфорт и эвкалиптовые рощи\nЕсли вы ищете идеальный баланс между дикой природой и комфортом, отправляйтесь в Parque de la Vallesa. Это зелёная зона, надёжно прикрытая кронами средиземноморских сосен и эвкалиптов. Здесь есть прочные деревянные столы и уютные тропы: безупречное место для долгого обеда, где дети могут свободно играть, а взрослые наслаждаются бокалом насыщенного красного вина из винограда Монастрель.\nАтмосфера: Безмятежность, семейное тепло и эстетика лесного пикника.\nАдрес: Carrer de la Vallesa, 03710 Calp, Alicante.",
    fr: "1. Parque de la Vallesa : Confort et boisements d'eucalyptus\nSi vous cherchez l'équilibre parfait entre nature sauvage et confort, rendez-vous au Parque de la Vallesa. C'est un espace vert soigneusement abrité par les cimes des pins méditerranéens et des eucalyptus. Vous y trouverez de solides tables en bois et des sentiers accueillants : un lieu impeccable pour un long repas où les enfants jouent librement pendant que les adultes savourent un verre de vin rouge intense de Monastrell.\nAtmosphère : Sérénité, chaleur familiale et esthétique d'un pique-nique en forêt.\nAdresse : Carrer de la Vallesa, 03710 Calp, Alicante.",
    it: "1. Parque de la Vallesa: Comfort e boschi di eucalipti\nSe cercate il perfetto equilibrio tra natura selvaggia e comfort, dirigetevi al Parque de la Vallesa. È un'area verde accuratamente protetta dalle chiome di pini mediterranei ed eucalipti. Troverete robusti tavoli in legno e sentieri accoglienti: un luogo impeccabile per un pasto lungo, dove i bambini giocano liberamente mentre gli adulti gustano un bicchiere di rosso intenso di Monastrell.\nAtmosfera: Serenità, calore familiare ed estetica di un picnic nel bosco.\nIndirizzo: Carrer de la Vallesa, 03710 Calp, Alicante.",
    de: "1. Parque de la Vallesa: Komfort und Eukalyptuswälder\nWenn Sie das perfekte Gleichgewicht zwischen wilder Natur und Komfort suchen, besuchen Sie den Parque de la Vallesa. Es ist eine Grünfläche, sorgsam beschattet von mediterranen Kiefern und Eukalypten. Hier finden Sie robuste Holztische und einladende Wege: ein makelloser Ort für ein langes Mahl, wo Kinder frei spielen können, während Erwachsene ein Glas kräftigen Rotweins von der Monastrell-Traube genießen.\nAtmosphäre: Gelassenheit, familiäre Wärme und die Ästhetik eines Waldpicknicks.\nAdresse: Carrer de la Vallesa, 03710 Calp, Alicante.",
    uk: "1. Parque de la Vallesa: Комфорт і евкаліптові гаї\nЯкщо ви шукаєте ідеальний баланс між дикою природою та комфортом, вирушайте до Parque de la Vallesa. Це зелена зона, надійно захищена кронами середземноморських сосен і евкаліптів. Тут є міцні дерев'яні столи та затишні стежки: бездоганне місце для тривалої трапези, де діти можуть вільно грати, а дорослі насолоджуються келихом насиченого червоного вина з винограду Монастрель.\nАтмосфера: Спокій, сімейне тепло та естетика лісового пікніка.\nАдреса: Carrer de la Vallesa, 03710 Calp, Alicante.",
    pl: "1. Parque de la Vallesa: Komfort i gaje eukaliptusowe\nJeśli szukasz idealnej równowagi między dziką naturą a komfortem, udaj się do Parque de la Vallesa. To zielona przestrzeń osłonięta koronami sosen śródziemnomorskich i eukaliptusów. Znajdziesz tu solidne drewniane stoły i przyjemne ścieżki: doskonałe miejsce na długi posiłek, gdzie dzieci mogą swobodnie się bawić, a dorośli delektują się kieliszkiem intensywnego czerwonego wina z odmiany Monastrell.\nAtmosfera: Spokój, rodzinne ciepło i estetyka pikniku w lesie.\nAdres: Carrer de la Vallesa, 03710 Calp, Alicante.",
  },
  expBBQParksModalSection2: {
    eng: "2. Monte Oltà: A picnic with panoramic views above the clouds\nFor those who want to rise above the bustle of the coast, there is a picturesque recreation area on the slopes of Monte Oltà (Zona de Acampada Oltà). The path winds through aromatic wild rosemary and thyme scrub, and from the summit opens a postcard view of the city’s symbol, the Peñón de Ifach, and the endless blue sea.\nAtmosphere: Mountain freshness, wild herb scents and the aesthetic of height.\nAddress: Partida Oltamar, s/n, 03710 Calp, Alicante.",
    esp: "2. Monte Oltà: Un pícnic con vistas panorámicas sobre las nubes\nPara aquellos que deseen elevarse por encima del bullicio de la costa, existe una pintoresca área recreativa en las laderas del monte Oltà (Zona de Acampada Oltà). El camino hasta aquí serpentea a través de aromáticos matorrales de romero silvestre y tomillo, y desde la cima se abre una impresionante vista de postal del símbolo de la ciudad, el Peñón de Ifach, y el infinito azul del mar.\nAtmósfera: Frescor de montaña, aroma a hierbas silvestres y la estética de la altura.\nDirección: Partida Oltamar, s/n, 03710 Calp, Alicante.",
    ru: "2. Монте-Ольта: Пикник с панорамой над облаками\nДля тех, кто хочет подняться над суетой побережья, на склонах Monte Oltà есть живописная зона отдыха (Zona de Acampada Oltà). Путь извивается среди ароматных зарослей дикого розмарина и чабреца, а с вершины открывается открыточный вид на символ города — Пеньон-де-Ифач — и бескрайнее синее море.\nАтмосфера: Горская свежесть, запахи диких трав и эстетика высоты.\nАдрес: Partida Oltamar, s/n, 03710 Calp, Alicante.",
    fr: "2. Monte Oltà : Un pique-nique avec vue panoramique au-dessus des nuages\nPour ceux qui souhaitent s'élever au-dessus de l'agitation du littoral, il existe une aire de loisirs pittoresque sur les pentes du Monte Oltà (Zona de Acampada Oltà). Le chemin serpente à travers des broussailles aromatiques de romarin sauvage et de thym, et du sommet s'ouvre une vue carte postale sur le symbole de la ville, le Peñón de Ifach, et l'infini bleu de la mer.\nAtmosphère : Fraîcheur de montagne, parfums d'herbes sauvages et esthétique de l'altitude.\nAdresse : Partida Oltamar, s/n, 03710 Calp, Alicante.",
    it: "2. Monte Oltà: Un picnic con vista panoramica sopra le nuvole\nPer chi desidera elevarsi sopra il frastuono della costa, c'è un'area ricreativa pittoresca sulle pendici del Monte Oltà (Zona de Acampada Oltà). Il sentiero serpeggia tra macchie aromatiche di rosmarino selvatico e timo, e dalla cima si apre una vista da cartolina sul simbolo della città, il Peñón de Ifach, e sull'infinito blu del mare.\nAtmosfera: Freschezza di montagna, profumi di erbe selvatiche ed estetica dell'altura.\nIndirizzo: Partida Oltamar, s/n, 03710 Calp, Alicante.",
    de: "2. Monte Oltà: Ein Picknick mit Panoramablick über den Wolken\nWer dem Trubel der Küste entfliehen möchte, findet am Monte Oltà (Zona de Acampada Oltà) ein malerisches Erholungsgebiet. Der Weg schlängelt sich durch duftiges Wildrosmarin und Thymian, und vom Gipfel eröffnet sich eine Postkartenansicht auf das Wahrzeichen der Stadt, den Peñón de Ifach, und das endlose Blau des Meeres.\nAtmosphäre: Bergfrische, Düfte wilder Kräuter und die Ästhetik der Höhe.\nAdresse: Partida Oltamar, s/n, 03710 Calp, Alicante.",
    uk: "2. Monte Oltà: Пікнік із панорамою над хмарами\nДля тих, хто хоче піднятися над метушнею узбережжя, на схилах Monte Oltà є мальовнича зона відпочинку (Zona de Acampada Oltà). Шлях в'ється крізь ароматні зарості дикого розмарину та чебрецю, а з вершини відкривається вид як на листівку на символ міста — Пеньйон-де-Іфач — і безкрайнє синє море.\nАтмосфера: Гірська свіжість, аромати диких трав і естетика висоти.\nАдреса: Partida Oltamar, s/n, 03710 Calp, Alicante.",
    pl: "2. Monte Oltà: Piknik z panoramicznym widokiem ponad chmurami\nDla tych, którzy chcą wznieść się ponad gwar wybrzeża, na stokach Monte Oltà (Zona de Acampada Oltà) znajduje się malowniczy teren rekreacyjny. Ścieżka wije się przez pachnące zarośla dzikiego rozmarynu i tymianku, a ze szczytu rozpościera się widok jak z pocztówki na symbol miasta, Peñón de Ifach, i nieskończoną błękit morza.\nAtmosfera: Górska świeżość, zapachy dzikich ziół i estetyka wysokości.\nAdres: Partida Oltamar, s/n, 03710 Calp, Alicante.",
  },
  expBBQParksModalSection3: {
    eng: "3. Seasonal aesthetics and care for nature\nIn Spain, forests are treated with immense respect. During the hottest months (from June to October), lighting outdoor fires and using stone barbecues in Calpe’s parks is strictly prohibited for the safety of nature. But that is no reason to give up on pleasure! Prepare tender cuts of premium Iberian pork or fresh langoustines on your Inftour villa grill, pack them in a beautiful basket with ham, artisan cheeses and ice-cold white wine, and head out to enjoy an aesthetic picnic in the shade of the trees.",
    esp: "3. Estética estacional y cuidado de la naturaleza\nEn España se trata a los bosques con un inmenso respeto. Durante los meses más calurosos (de junio a octubre), encender fuego al aire libre y usar las barbacoas de piedra en los parques de Calpe está estrictamente prohibido por la seguridad de la naturaleza. ¡Pero eso no es motivo para renunciar al placer! Prepare tiernos cortes de cerdo ibérico premium o cigalas frescas en la parrilla de su villa Inftour, empaquételos en una hermosa cesta junto con jamón, quesos artesanales y un vino blanco helado, y diríjase a disfrutar de un estético pícnic a la sombra de los árboles.",
    ru: "3. Сезонная эстетика и забота о природе\nВ Испании к лесам относятся с огромным уважением. В самые жаркие месяцы (с июня по октябрь) разжигание огня на открытом воздухе и использование каменных мангалов в парках Кальпе строго запрещены ради безопасности природы. Но это не повод отказываться от удовольствия! Приготовьте на гриле виллы Inftour нежные куски премиального иберийского мяса или свежие лангустины, сложите всё в красивую корзину вместе с хамоном, ремесленными сырами и ледяным белым вином и отправляйтесь на эстетичный пикник в тени деревьев.",
    fr: "3. Esthétique saisonnière et respect de la nature\nEn Espagne, les forêts sont traitées avec un immense respect. Pendant les mois les plus chauds (de juin à octobre), allumer un feu en plein air et utiliser les barbecues en pierre dans les parcs de Calpe est strictement interdit pour la sécurité de la nature. Ce n’est pourtant pas une raison de renoncer au plaisir ! Préparez sur le grill de votre villa Inftour des morceaux tendres de porc ibérique premium ou des langoustines fraîches, mettez-les dans un joli panier avec du jambon, des fromages artisanaux et un vin blanc glacé, puis partez savourer un pique-nique esthétique à l’ombre des arbres.",
    it: "3. Estetica stagionale e cura della natura\nIn Spagna i boschi sono trattati con immenso rispetto. Nei mesi più caldi (da giugno a ottobre) accendere fuochi all’aperto e usare i barbecue in pietra nei parchi di Calpe è severamente vietato per la sicurezza della natura. Ma non è motivo per rinunciare al piacere! Preparate sulla griglia della vostra villa Inftour teneri tagli di maiale iberico premium o scampi freschi, metteteli in un bel cestino con prosciutto, formaggi artigianali e vino bianco ghiacciato, e godetevi un picnic estetico all’ombra degli alberi.",
    de: "3. Saisonale Ästhetik und Naturschutz\nIn Spanien werden Wälder mit großem Respekt behandelt. In den heißesten Monaten (Juni bis Oktober) sind offenes Feuer und die Nutzung der Steingrills in Calpes Parks zum Schutz der Natur streng verboten. Das ist aber kein Grund auf Genuss zu verzichten! Bereiten Sie auf dem Grill Ihrer Inftour-Villa zarte Stücke von premium Iberico-Schwein oder frische Kaisergranate zu, packen Sie sie mit Schinken, handwerklichen Käsesorten und eiskaltem Weißwein in einen schönen Korb und genießen Sie ein stimmungsvolles Picknick im Schatten der Bäume.",
    uk: "3. Сезонна естетика та турбота про природу\nВ Іспанії до лісів ставляться з величезною повагою. У найспекотніші місяці (з червня по жовтень) розпалювання вогню на відкритому повітрі та використання кам’яних мангалів у парках Кальпе суворо заборонені заради безпеки природи. Але це не привід відмовлятися від задоволення! Приготуйте на грилі вілли Inftour ніжні шматочки преміального іберійського м’яса або свіжих лангустинів, покладіть у красивий кошик разом із хамоном, ремісничими сырами та крижаним білим вином і вирушайте на естетичний пікнік у тіні дерев.",
    pl: "3. Sezonowa estetyka i troska o naturę\nW Hiszpanii do lasów podchodzi się z ogromnym szacunkiem. W najgorętszych miesiącach (od czerwca do października) rozpalanie ognia na świeżym powietrzu i korzystanie z kamiennych grilli w parkach Calpe jest surowo zabronione ze względu na bezpieczeństwo przyrody. To jednak nie powód, by rezygnować z przyjemności! Przygotuj na grillu willi Inftour delikatne kawałki premiumowej wieprzowiny iberyjskiej lub świeże langustyny, spakuj je do pięknego kosza z szynką, serami rzemieślniczymi i lodowatym białym winem i wybierz się na estetyczny piknik w cieniu drzew.",
  },
  expBBQParksModalSection4Lead: {
    eng: "4. Children's spaces: The art of resting together\nCalpe offers young guests as much fun as their parents. Play areas here are designed so adults can relax and enjoy the moment too.",
    esp: "4. Espacios infantiles: El arte de descansar juntos\nCalpe ofrece a los pequeños invitados tanta diversión como a sus padres. Las zonas de juego aquí están diseñadas para que los adultos también puedan relajarse y disfrutar del momento.",
    ru: "4. Детские пространства: Искусство отдыхать вместе\nКальпе дарит маленьким гостям столько же радости, сколько родителям. Игровые зоны здесь устроены так, чтобы взрослые тоже могли расслабиться и насладиться моментом.",
    fr: "4. Espaces pour enfants : L'art de se reposer ensemble\nCalpe offre aux petits invités autant de plaisir qu'à leurs parents. Les aires de jeu sont conçues pour que les adultes puissent aussi se détendre et profiter de l'instant.",
    it: "4. Spazi per bambini: L'arte di riposare insieme\nCalpe offre ai piccoli ospiti tanto divertimento quanto ai genitori. Le aree gioco sono pensate perché anche gli adulti possano rilassarsi e godersi il momento.",
    de: "4. Kinderspielbereiche: Die Kunst, gemeinsam auszuspannen\nCalpe bietet kleinen Gästen ebenso viel Spaß wie den Eltern. Die Spielbereiche sind so gestaltet, dass auch Erwachsene entspannen und den Moment genießen können.",
    uk: "4. Дитячі простори: Мистецтво відпочивати разом\nКальпе дарує маленьким гостям стільки ж радості, скільки батькам. Ігрові зони створені так, щоб дорослі теж могли розслабитися і насолодитися моментом.",
    pl: "4. Przestrzenie dla dzieci: Sztuka wspólnego odpoczynku\nCalpe daje małym gościom tyle samo radości co rodzicom. Strefy zabaw są zaprojektowane tak, by dorośli też mogli się zrelaksować i cieszyć chwilą.",
  },
  expBBQParksModalSection4Spot1: {
    eng: "Beach playgrounds Arenal-Bol and La Fossa\nJust above the soft golden sand of the main beaches, excellent play complexes shaped like pirate ships and castles are set up. Children play barefoot with the sound of the waves in the background, while you can watch from a sun lounger or from the terrace of the nearest café with a morning coffee.\nAddress (Arenal-Bol): Paseo Marítimo Infanta Elena, 03710 Calp, Alicante.\nAddress (La Fossa): Paseo Marítimo Infanta Cristina, 03710 Calp, Alicante.",
    esp: "Parques de playa Arenal-Bol y La Fossa\nJusto sobre la suave arena dorada de las playas principales se instalan excelentes complejos de juego en forma de barcos piratas y castillos. Los niños juegan descalzos con el sonido de las olas de fondo, mientras usted puede observarlos desde una tumbona o desde la terraza de la cafetería más cercana con una taza de café matutino.\nDirección (Arenal-Bol): Paseo Marítimo Infanta Elena, 03710 Calp, Alicante.\nDirección (La Fossa): Paseo Marítimo Infanta Cristina, 03710 Calp, Alicante.",
    ru: "Пляжные площадки Arenal-Bol и La Fossa\nПрямо над мягким золотым песком главных пляжей установлены отличные игровые комплексы в виде пиратских кораблей и замков. Дети играют босиком на фоне шума волн, а вы можете наблюдать за ними с шезлонга или с террасы ближайшего кафе с утренним кофе.\nАдрес (Arenal-Bol): Paseo Marítimo Infanta Elena, 03710 Calp, Alicante.\nАдрес (La Fossa): Paseo Marítimo Infanta Cristina, 03710 Calp, Alicante.",
    fr: "Aires de jeux de plage Arenal-Bol et La Fossa\nJuste au-dessus du sable doré des plages principales s’installent d’excellents complexes de jeux en forme de bateaux pirates et de châteaux. Les enfants jouent pieds nus au bruit des vagues en arrière-plan, pendant que vous les surveillez depuis un transat ou la terrasse du café le plus proche avec un café du matin.\nAdresse (Arenal-Bol) : Paseo Marítimo Infanta Elena, 03710 Calp, Alicante.\nAdresse (La Fossa) : Paseo Marítimo Infanta Cristina, 03710 Calp, Alicante.",
    it: "Parchi giochi sulla spiaggia Arenal-Bol e La Fossa\nProprio sulla sabbia dorata delle spiagge principali compaiono ottimi complessi gioco a forma di navi pirata e castelli. I bambini giocano a piedi nudi con il suono delle onde sullo sfondo, mentre voi potete guardarli da uno sdraio o dalla terrazza del bar più vicino con una tazza di caffè del mattino.\nIndirizzo (Arenal-Bol): Paseo Marítimo Infanta Elena, 03710 Calp, Alicante.\nIndirizzo (La Fossa): Paseo Marítimo Infanta Cristina, 03710 Calp, Alicante.",
    de: "Strandspielplätze Arenal-Bol und La Fossa\nDirekt über dem weichen goldenen Sand der Hauptstrände stehen großartige Spielanlagen in Form von Piratenschiffen und Burgen. Kinder spielen barfuß mit dem Wellenrauschen im Hintergrund, während Sie sie vom Liegestuhl oder von der Terrasse des nächsten Cafés mit einer Morgentasse Kaffee beobachten können.\nAdresse (Arenal-Bol): Paseo Marítimo Infanta Elena, 03710 Calp, Alicante.\nAdresse (La Fossa): Paseo Marítimo Infanta Cristina, 03710 Calp, Alicante.",
    uk: "Пляжні майданчики Arenal-Bol і La Fossa\nПрямо над м’яким золотим піском головних пляжів встановлюють чудові ігрові комплекси у формі піратських кораблів і замків. Діти грають босоніж на тлі шуму хвиль, а ви можете спостерігати з шезлонга чи з тераси найближчої кав’ярні з ранковою кавою.\nАдреса (Arenal-Bol): Paseo Marítimo Infanta Elena, 03710 Calp, Alicante.\nАдреса (La Fossa): Paseo Marítimo Infanta Cristina, 03710 Calp, Alicante.",
    pl: "Place zabaw na plaży Arenal-Bol i La Fossa\nTuż nad miękkim złotym piaskiem głównych plaż stoją świetne place zabaw w kształcie pirackich statków i zamków. Dzieci biegają boso przy szumie fal, a Wy możecie je obserwować z leżaka lub z tarasu najbliższej kawiarni z poranną kawą.\nAdres (Arenal-Bol): Paseo Marítimo Infanta Elena, 03710 Calp, Alicante.\nAdres (La Fossa): Paseo Marítimo Infanta Cristina, 03710 Calp, Alicante.",
  },
  expBBQParksModalSection4Spot2: {
    eng: "Creativity Park\nA modern urban oasis. Its safe surfacing, well-designed play zones for different ages and comfortable benches make it a favourite for family strolls.\nAddress: Partida Gargasindi, 03710 Calp, Alicante.",
    esp: "Parque de la Creatividad\nUn moderno oasis urbano. Su suelo seguro, sus zonas de desarrollo bien pensadas para niños de diferentes edades y sus cómodos bancos lo convierten en el lugar favorito para los paseos familiares.\nDirección: Partida Gargasindi, 03710 Calp, Alicante.",
    ru: "Парк творчества (Parque de la Creatividad)\nСовременный городской оазис. Безопасное покрытие, продуманные зоны для разных возрастов и удобные скамейки делают его любимым местом для семейных прогулок.\nАдрес: Partida Gargasindi, 03710 Calp, Alicante.",
    fr: "Parc de la Créativité\nUne oasis urbaine moderne. Son sol sécurisé, ses aires de jeu pensées pour différents âges et ses bancs confortables en font le lieu privilégié des promenades en famille.\nAdresse : Partida Gargasindi, 03710 Calp, Alicante.",
    it: "Parco della Creatività\nUn moderno oasi urbana. Pavimentazione sicura, aree gioco studiate per diverse età e comode panchine lo rendono il preferito per le passeggiate in famiglia.\nIndirizzo: Partida Gargasindi, 03710 Calp, Alicante.",
    de: "Kreativitätspark (Parque de la Creatividad)\nEine moderne städtische Oase. Sicherer Boden, durchdachte Spielbereiche für verschiedene Altersgruppen und bequeme Bänke machen ihn zum Lieblingsort für Familienspaziergänge.\nAdresse: Partida Gargasindi, 03710 Calp, Alicante.",
    uk: "Парк творчості (Parque de la Creatividad)\nСучасна міська оаза. Безпечне покриття, продумані зони для різних віків і зручні лави роблять його улюбленим місцем для сімейних прогулянок.\nАдреса: Partida Gargasindi, 03710 Calp, Alicante.",
    pl: "Park Kreatywności (Parque de la Creatividad)\nNowoczesna miejska oaza. Bezpieczna nawierzchnia, przemyślane strefy zabaw dla różnych grup wiekowych i wygodne ławki czynią go ulubionym miejscem rodzinnych spacerów.\nAdres: Partida Gargasindi, 03710 Calp, Alicante.",
  },
  expBBQParksModalTip: {
    eng: "INFTOUR tip: In Spain, life follows the sun, and local playgrounds really come alive from 6 p.m. when the daytime heat fades. Save yourself long searches — our intelligent AI assistant will instantly tell you which parks in Calpe offer the best shade in the morning and help you find the ideal spot to unwind.",
    esp: "Consejo de Inftour: La vida en España la dicta el sol, y los parques infantiles locales cobran vida solo a partir de las 18:00, cuando el calor diurno disminuye. Ahórrese largas búsquedas: nuestro asistente inteligente de IA le indicará al instante qué parques de Calpe ofrecen la mejor sombra en las horas de la mañana y le ayudará a encontrar el lugar ideal para su descanso.",
    ru: "Совет INFTOUR: В Испании всё подчинено солнцу, и местные детские площадки оживают по-настоящему с 18:00, когда спадает дневная жара. Не тратьте время на долгие поиски — наш интеллектуальный AI-ассистент мгновенно подскажет, какие парки в Кальпе дают лучшую тень утром, и поможет найти идеальное место для отдыха.",
    fr: "Conseil INFTOUR : En Espagne, c’est le soleil qui mène la danse, et les aires de jeu locales ne prennent vraiment vie qu’à partir de 18 h, quand la chaleur du jour retombe. Évitez de longues recherches : notre assistant IA intelligent vous indiquera aussitôt quels parcs de Calpe offrent le meilleur ombrage le matin et vous aidera à trouver l’endroit idéal pour vous détendre.",
    it: "Consiglio INFTOUR: In Spagna comanda il sole, e i parchi giochi locali prendono vita soprattutto dalle 18:00, quando cala il calore diurno. Risparmiate lunghe ricerche: il nostro assistente IA intelligente vi dirà subito quali parchi a Calpe offrono l’ombra migliore al mattino e vi aiuterà a trovare il posto ideale per rilassarvi.",
    de: "INFTOUR-Tipp: In Spanien bestimmt die Sonne den Rhythmus, und die örtlichen Spielplätze werden erst ab 18 Uhr richtig lebendig, wenn die Tageshitze nachlässt. Sparen Sie sich lange Sucherei — unser intelligenter KI-Assistent sagt Ihnen sofort, welche Parks in Calpe vormittags den besten Schatten bieten, und hilft Ihnen, den idealen Ort zum Ausspannen zu finden.",
    uk: "Порада INFTOUR: В Іспанії ритм задає сонце, а місцеві дитячі майданчики по-справжньому оживають з 18:00, коли спадає денна спека. Заощадьте час на довгі пошуки — наш інтелектуальний ШІ-асистент миттєво підкаже, які парки в Кальпе дають найкращу тінь зранку, і допоможе знайти ідеальне місце для відпочинку.",
    pl: "Wskazówka INFTOUR: W Hiszpanii rytm wyznacza słońce, a lokalne place zabaw tętnią życiem dopiero od 18:00, gdy mija dzienny upał. Oszczędź sobie długich poszukiwań — nasz inteligentny asystent AI od razu wskaże, które parki w Calpe dają najlepszy cień rano, i pomoże znaleźć idealne miejsce na relaks.",
  },
};
