type LangStrings = {
  eng: string;
  esp: string;
  ru: string;
  fr: string;
  it: string;
  de: string;
  uk: string;
  pl: string;
};

/** Family Park Calpe / feria local — from Feria local de atracciones.docx */
export const feriaModalTranslations: Record<string, LangStrings> = {
  expFeriaModalTitle: {
    eng: "Family Park Calpe: the local amusement park",
    esp: "Family Park Calpe: el parque de atracciones local",
    ru: "Family Park Calpe: местный парк аттракционов",
    fr: "Family Park Calpe : le parc d'attractions local",
    it: "Family Park Calpe: il parco divertimenti locale",
    de: "Family Park Calpe: der lokale Freizeitpark",
    uk: "Family Park Calpe: локальний парк атракціонів",
    pl: "Family Park Calpe: lokalny park rozrywki",
  },
  expFeriaModalSubtitle: {
    eng: "Vintage charm and the magic of Mediterranean evenings",
    esp: "Encanto vintage y la magia de las tardes mediterráneas",
    ru: "Винтажное очарование и магия средиземноморских вечеров",
    fr: "Charme vintage et magie des soirées méditerranéennes",
    it: "Fascino vintage e la magia dei pomeriggi mediterranei",
    de: "Vintage-Charme und die Magie mediterraner Abende",
    uk: "Вінтажний шарм і магія середземноморських вечорів",
    pl: "Urok vintage i magia śródziemnomorskich wieczorów",
  },
  expFeriaModalIntro: {
    eng: "After the dizzying G-forces of the giant parks in Benidorm, it is time to enjoy a completely different and more intimate aesthetic. An authentic Spanish summer is inconceivable without the traditional local fair. Family Park in Calpe is a portal to those warm and carefree evenings of your own childhood, with the aroma of cotton candy, warm caramel, and the salty sea breeze.",
    esp: "Tras las vertiginosas fuerzas G de los gigantescos parques de Benidorm, llega el momento de disfrutar de una estética completamente diferente y más íntima. Un auténtico verano español es inconcebible sin la tradicional feria local. Family Park en Calpe es un portal a esas tardes cálidas y despreocupadas de su propia infancia, con aroma a algodón de azúcar, caramelo caliente y la brisa salada del mar.",
    ru: "После головокружительных перегрузок гигантских парков Бенидорма наступает время совсем другой, более камерной эстетики. Подлинное испанское лето немыслимо без традиционной местной ярмарки. Family Park в Кальпе — это портал в те тёплые и беззаботные вечера вашего детства: запах сахарной ваты, горячей карамели и солёного морского бриза.",
    fr: "Après les forces G vertigineuses des parcs géants de Benidorm, vient le moment de savourer une esthétique complètement différente et plus intime. Un véritable été espagnol est inconcevable sans la fête foraine locale traditionnelle. Le Family Park de Calpe est une porte vers ces soirées chaudes et insouciantes de votre propre enfance, avec l'arôme de barbe à papa, du caramel chaud et la brise salée de la mer.",
    it: "Dopo le vertiginose forze G dei giganteschi parchi di Benidorm, arriva il momento di godersi un'estetica completamente diversa e più intima. Un'autentica estate spagnola è inconcepibile senza la tradizionale fiera locale. Il Family Park a Calpe è un portale verso quei pomeriggi caldi e spensierati della propria infanzia, con l'aroma di zucchero filato, caramello caldo e la brezza salata del mare.",
    de: "Nach den schwindelerregenden G-Kräften der Riesenparks in Benidorm ist es an der Zeit, eine ganz andere, intimere Ästhetik zu genießen. Ein authentischer spanischer Sommer ist ohne die traditionelle lokale Kirmes undenkbar. Der Family Park in Calpe ist ein Tor zu jenen warmen, unbeschwerten Abenden Ihrer eigenen Kindheit – mit dem Duft von Zuckerwatte, warmem Karamell und der salzigen Meeresbrise.",
    uk: "Після запаморочливих G-сил гігантських парків Бенідорма настає час зовсім іншої, більш камерної естетики. Справжнє іспанське літо неможливе без традиційної місцевої ярмарки. Family Park у Кальпе — це портал у ті теплі та безтурботні вечори вашого дитинства: аромат цукрової вати, гарячої карамелі та солоного морського бризу.",
    pl: "Po zapierających dech w piersiach przeciążeniach w gigantycznych parkach w Benidormie przychodzi czas na zupełnie inną, bardziej kameralną estetykę. Autentyczne hiszpańskie lato bez tradycyjnej lokalnej ferii jest nie do wyobrażenia. Family Park w Calpe to portal do tych ciepłych, beztroskich wieczorów z własnego dzieciństwa: zapach waty cukrowej, gorącego karmelu i słonej morskiej bryzy.",
  },
  expFeriaModalSection1: {
    eng: "An oasis next to the Pink Lake\nThe park enjoys a phenomenal location: right next to the famous salt lake of Las Salinas. The ideal setting for a family evening is as follows: at sunset, take a quiet stroll by the lake, watching the pink flamingos prepare for sleep. And then, when twilight envelops the city, dive into a sea of bright lights, music, and laughter at the amusement park.",
    esp: "Un oasis junto al Lago Rosa\nEl parque goza de una ubicación fenomenal: justo al lado del famoso lago salado de Las Salinas. El escenario ideal para una velada en familia es el siguiente: al atardecer, pasean tranquilamente junto al lago, observando cómo los flamencos rosados se preparan para dormir. Y luego, cuando el crepúsculo envuelve la ciudad, se sumergen en un mar de luces brillantes, música y risas en el parque de atracciones.",
    ru: "Оазис у Розового озера\nПарк занимает феноменальное место: прямо рядом со знаменитым солёным озером Las Salinas. Идеальный семейный вечер может выглядеть так: на закате неспешная прогулка вдоль озера, наблюдение за розовыми фламинго, готовящимися ко сну. А затем, когда сумерки окутывают город, вы погружаетесь в море ярких огней, музыки и смеха в парке аттракционов.",
    fr: "Une oasis au bord du lac rose\nLe parc bénéficie d'un emplacement phénoménal : juste à côté du célèbre lac salé de Las Salinas. Le cadre idéal pour une soirée en famille : au coucher du soleil, promenez-vous tranquillement au bord du lac en observant les flamants roses se préparer à dormir. Puis, lorsque le crépuscule enveloppe la ville, plongez dans une mer de lumières vives, de musique et de rires au parc d'attractions.",
    it: "Un'oasi accanto al Lago Rosa\nIl parco gode di una posizione fenomenale: proprio accanto al famoso lago salato di Las Salinas. Lo scenario ideale per una serata in famiglia: al tramonto una passeggiata tranquilla lungo il lago osservando i fenicotteri rosa che si preparano a dormire. Poi, quando il crepuscolo avvolge la città, vi tuffate in un mare di luci, musica e risate al parco divertimenti.",
    de: "Eine Oase am Rosa See\nDer Park hat eine phänomenale Lage: direkt neben dem berühmten Salzsee Las Salinas. Das ideale Familienabendprogramm: Bei Sonnenuntergang gemütlich am See spazieren und die rosa Flamingos beim Zur-Ruhe-Kommen beobachten. Wenn die Dämmerung die Stadt umhüllt, tauchen Sie ein in ein Meer aus Lichtern, Musik und Gelächter im Freizeitpark.",
    uk: "Оаза біля Рожевого озера\nПарк займає феноменальне місце: одразу біля знаменитого солоного озера Las Salinas. Ідеальний сімейний вечір: на заході сонця — неспішна прогулянка вздовж озера, спостереження за рожевими фламінго, що готуються до сну. А потім, коли сутінки огортають місто, ви поринаєте в море вогнів, музики та сміху в парку атракціонів.",
    pl: "Oaza przy Różowym Jeziorze\nPark ma fenomenalną lokalizację: tuż obok słynnego słonego jeziora Las Salinas. Idealny wieczór z rodziną: o zachodzie słońca spokojny spacer wzdłuż jeziora z obserwacją różowych flamingów szykujących się do snu. Potem, gdy zmrok otula miasto, zanurzacie się w morzu świateł, muzyki i śmiechu w parku rozrywki.",
  },
  expFeriaModalSection2: {
    eng: "Pure childhood enthusiasm\nThis park is an absolute paradise for children up to 12 years old. Here, the golden age of classics comes together: from the fun caterpillar-shaped roller coaster Brocomela and the pirate ship to trampolines and traditional bumper cars. It is a very compact, intuitive, and safe space. Children can run freely from one attraction to another, and you won't have to worry about them getting lost in the crowd, as often happens in giant leisure complexes.",
    esp: "Entusiasmo infantil en estado puro\nEste parque es un paraíso absoluto para los niños de hasta 12 años. Aquí se reúne la época dorada de los clásicos: desde la divertida montaña rusa en forma de oruga Brocomela y el barco pirata, hasta las camas elásticas y los tradicionales coches de choque. Es un espacio muy compacto, intuitivo y seguro. Los niños pueden correr libremente de una atracción a otra, y usted no tendrá que preocuparse de que se pierdan entre la multitud, como suele ocurrir en los gigantescos complejos de ocio.",
    ru: "Чистый детский энтузиазм\nЭтот парк — настоящий рай для детей до 12 лет. Здесь собрана золотая эпоха классики: от весёлой американской горки в виде гусеницы Brocomela и пиратского корабля до батутов и традиционных автодромов. Пространство очень компактное, понятное и безопасное. Дети могут свободно бегать от одного аттракциона к другому, и вам не придётся бояться, что они потеряются в толпе, как это бывает в гигантских развлекательных комплексах.",
    fr: "L'enthousiasme enfantin à l'état pur\nCe parc est un paradis absolu pour les enfants jusqu'à 12 ans. On y retrouve l'âge d'or des classiques : de la joyeuse montagne russe en forme de chenille Brocomela au bateau pirate, en passant par les trampolines et les autos tamponneuses traditionnelles. C'est un espace très compact, intuitif et sûr. Les enfants peuvent courir librement d'une attraction à l'autre sans que vous n'ayez à craindre qu'ils se perdent dans la foule, comme c'est souvent le cas dans les complexes géants.",
    it: "Entusiasmo infantile allo stato puro\nQuesto parco è un paradiso assoluto per i bambini fino a 12 anni. Qui si riunisce l'età d'oro dei classici: dalla divertente montagna russa a forma di bruco Brocomela alla nave pirata, passando per i trampolini e le tradizionali auto tamponamento. È uno spazio molto compatto, intuitivo e sicuro. I bambini possono correre liberamente da un'attrazione all'altra e non dovrete temere che si perdano tra la folla, come spesso accade nei complessi giganteschi.",
    de: "Kinderbegeisterung in Reinform\nDieser Park ist ein absolutes Paradies für Kinder bis 12 Jahre. Hier trifft die goldene Ära der Klassiker zusammen: von der lustigen Raupe-Achterbahn Brocomela und dem Piratenschiff bis zu Trampolins und traditionellen Autoscootern. Es ist ein sehr kompakter, intuitiver und sicherer Ort. Kinder können frei von einer Attraktion zur nächsten rennen, ohne dass Sie befürchten müssen, sie gehen in der Menge verloren – wie in riesigen Freizeitkomplexen oft der Fall.",
    uk: "Дитячий ентузіазм у чистому вигляді\nЦей парк — справжній рай для дітей до 12 років. Тут зібрана золота доба класики: від веселої гірки-гусениці Brocomela та піратського корабля до батутів і традиційних бампер-карів. Простір дуже компактний, зрозумілий і безпечний. Діти можуть вільно бігати від одного атракціону до іншого, а ви не хвилюватиметеся, що вони загубляться в натовпі, як це часто буває в гігантських розважальних комплексах.",
    pl: "Czysty dziecięcy entuzjazm\nTen park to absolutny raj dla dzieci do 12 roku życia. Zebrano tu złotą erę klasyków: od zabawnej kolejki górskiej w kształcie gąsienicy Brocomela i statku pirackiego po trampoliny i tradycyjne autka (bumper cars). To przestrzeń bardzo kompaktowa, intuicyjna i bezpieczna. Dzieci mogą swobodnie biegać od jednej atrakcji do drugiej, a Państwo nie muszą martwić się, że zgubią się w tłumie, co często zdarza się w gigantycznych kompleksach rozrywki.",
  },
  expFeriaModalSection3: {
    eng: "Aesthetics for parents\nThe main advantage of the local park is the absence of complicated logistics. You don't have to travel anywhere: Family Park is right in Calpe. While the children storm the carousels for the tenth time with sparkling eyes, adults can relax. Buy a portion of crispy, hot Spanish churros at the local stand, sit on a bench under the warm light of the garlands, and simply enjoy the moment, gazing at the absolutely happy faces of your little ones.",
    esp: "Estética para los padres\nLa principal ventaja del parque local es la ausencia de una logística complicada. No tiene que desplazarse a ningún lado: Family Park está justo en Calpe. Mientras los niños asaltan los carruseles por décima vez con los ojos brillantes, los adultos pueden relajarse. Compre una ración de churros españoles crujientes y ardientes en el puesto local, siéntese en un banco bajo la cálida luz de las guirnaldas y simplemente disfrute del momento, contemplando los rostros absolutamente felices de sus pequeños.",
    ru: "Эстетика для родителей\nГлавное преимущество местного парка — отсутствие сложной логистики. Никуда ехать не нужно: Family Park находится прямо в Кальпе. Пока дети в десятый раз с сияющими глазами штурмуют карусели, взрослые могут расслабиться. Купите порцию хрустящих горячих испанских чуррос в киоске, сядьте на скамейку в тёплом свете гирлянд и просто наслаждайтесь моментом, глядя на абсолютно счастливые лица малышей.",
    fr: "Esthétique pour les parents\nLe principal avantage du parc local est l'absence de logistique compliquée. Vous n'avez pas besoin de vous déplacer : le Family Park est en plein cœur de Calpe. Pendant que les enfants prennent d'assaut les carrousels pour la dixième fois les yeux brillants, les adultes peuvent se détendre. Achetez une portion de churros espagnols croustillants et brûlants au stand local, asseyez-vous sur un banc sous la lumière chaude des guirlandes et profitez simplement du moment en contemplant les visages absolument heureux de vos petits.",
    it: "Estetica per i genitori\nIl principale vantaggio del parco locale è l'assenza di logistica complicata. Non dovete spostarvi da nessuna parte: il Family Park è proprio a Calpe. Mentre i bambini assaltano per la decima volta le giostre con gli occhi lucidi, gli adulti possono rilassarsi. Comprate una porzione di churros spagnoli croccanti e fumanti al chiosco, sedetevi su una panchina sotto la calda luce delle ghirlande e godetevi semplicemente il momento guardando i volti assolutamente felici dei vostri piccoli.",
    de: "Ästhetik für Eltern\nDer Hauptvorteil des lokalen Parks ist das Fehlen komplizierter Logistik. Sie müssen nirgendwo hinfahren: Der Family Park liegt mitten in Calpe. Während die Kinder zum zehnten Mal mit funkelnden Augen die Karussells stürmen, können sich die Erwachsenen entspannen. Kaufen Sie eine Portion knusprige, heiße spanische Churros am Stand, setzen Sie sich unter das warme Licht der Lichterketten auf eine Bank und genießen Sie den Moment beim Anblick der strahlenden Gesichter Ihrer Kleinen.",
    uk: "Естетика для батьків\nГоловна перевага місцевого парку — відсутність складної логістики. Нікуди їхати не потрібно: Family Park — прямо в Кальпе. Поки діти вдесяте з блискучими очима штурмують каруселі, дорослі можуть відпочити. Купіть порцію хрустких гарячих іспанських чуррос у кіоску, сядьте на лаву в теплому світлі гірлянд і просто насолоджуйтеся моментом, дивлячись на абсолютно щасливі обличчя малюків.",
    pl: "Estetyka dla rodziców\nGłówną zaletą lokalnego parku jest brak skomplikowanej logistyki. Nie musicie Państwo nigdzie dojeżdżać: Family Park znajduje się w samym Calpe. Podczas gdy dzieci z błyszczącymi oczami po raz dziesiąty szturmują karuzele, dorośli mogą odpocząć. Kupcie porcję chrupiących, gorących hiszpańskich churros na stoisku, usiądźcie na ławce w ciepłym świetle girland i po prostu cieszcie się chwilą, patrząc na absolutnie szczęśliwe twarze maluchów.",
  },
  expFeriaModalTip: {
    eng: "INFTOUR tip: In local parks, paying for each attraction separately can be an unpleasant surprise, as children will want to ride everything five times. The secret to a peaceful rest is the special unlimited wristband (Pulsera). Our intelligent AI assistant is ready at any time to tell you the current price of this wristband and check the exact opening hours of Family Park (in summer, these places only come to life from 18:30, when the heat of the day subsides).",
    esp: "Consejo de Inftour: En los parques locales, pagar por cada atracción por separado puede resultar una sorpresa desagradable, ya que los niños querrán subirse a todo cinco veces. El secreto para un descanso tranquilo es la pulsera especial ilimitada (Pulsera). Nuestro asistente inteligente de IA está listo en cualquier momento para indicarle el precio actual de esta pulsera y comprobar los horarios exactos de apertura de Family Park (en verano, estos lugares solo cobran vida a partir de las 18:30, cuando disminuye el calor del día).",
    ru: "Совет INFTOUR: В местных парках оплата каждого аттракциона отдельно может стать неприятным сюрпризом — дети захотят прокатиться на всём по пять раз. Секрет спокойного отдыха — специальный безлимитный браслет (Pulsera). Наш интеллектуальный AI-ассистент в любой момент подскажет актуальную цену браслета и точные часы работы Family Park (летом такие места оживают только с 18:30, когда спадает дневная жара).",
    fr: "Conseil INFTOUR : Dans les parcs locaux, payer chaque attraction séparément peut être une surprise désagréable, car les enfants voudront tout faire cinq fois. Le secret d'un repos serein est le bracelet spécial illimité (Pulsera). Notre assistant IA intelligent est prêt à tout moment à vous indiquer le prix actuel de ce bracelet et à vérifier les horaires d'ouverture exacts du Family Park (en été, ces lieux ne s'animent qu'à partir de 18h30, quand la chaleur du jour diminue).",
    it: "Consiglio INFTOUR: Nei parchi locali pagare ogni attrazione separatamente può essere una brutta sorpresa: i bambini vorranno salire su tutto cinque volte. Il segreto per un riposo tranquillo è il braccialetto speciale illimitato (Pulsera). Il nostro assistente IA intelligente è pronto in qualsiasi momento a indicarvi il prezzo attuale del braccialetto e a verificare gli orari esatti di apertura del Family Park (in estate questi luoghi prendono vita solo dalle 18:30, quando cala il calore diurno).",
    de: "INFTOUR-Tipp: In lokalen Parks kann die Einzelzahlung pro Attraktion eine unangenehme Überraschung sein – Kinder wollen alles fünfmal fahren. Das Geheimnis entspannten Ausruhens ist das spezielle Unlimited-Armband (Pulsera). Unser intelligenter KI-Assistent nennt Ihnen jederzeit den aktuellen Preis dieses Armbands und prüft die genauen Öffnungszeiten des Family Park (im Sommer erwachen solche Orte erst ab 18:30 zum Leben, wenn die Tageshitze nachlässt).",
    uk: "Порада INFTOUR: У місцевих парках оплата кожного атракціону окремо може стати неприємним сюрпризом — діти захочуть покататися на всьому по п’ять разів. Секрет спокійного відпочинку — спеціальний безлімітний браслет (Pulsera). Наш інтелектуальний ШІ-асистент у будь-який момент підкаже актуальну ціну браслета та точний графік роботи Family Park (влітку такі місця оживають лише з 18:30, коли спадає денна спека).",
    pl: "Wskazówka INFTOUR: W lokalnych parkach płacenie za każdą atrakcję oddzielnie może okazać się nieprzyjemną niespodzianką — dzieci będą chciały skorzystać ze wszystkiego pięć razy. Sekretem spokojnego odpoczynku jest specjalna nielimitowana opaska (Pulsera). Nasz inteligentny asystent AI jest gotowy w każdej chwili podać aktualną cenę opaski i sprawdzić dokładne godziny otwarcia Family Park (latem miejsca te ożywają dopiero od 18:30, gdy upał dnia opada).",
  },
};
